### ISSUE TITLE
is there a way to load a local font to make configuration more portable?

### ISSUE THREAD

**Issue by kitcarsongit** [equalsraf/neovim-qt#1002]
Hi, maybe it's more a neovim question than a neovim-gui once but perhaps you can provide me an answer as well. 
Is there a way i can set guifont to a font located in my config directory without having to install it on the system?
Sorry if OT.

**Comment by jgehrig** [comment]
@kitcarsongit 

Marking as closed -- We do not support side-loading fonts in neovim-qt.

I think such a features is possible with Qt, but I don't plan on supporting such an option at the moment.

---

Feel free to continue the discussion here.

How to solve this problem is probably highly dependent on the platforms you're running and what you want to happen.

You could probably write some scripts on MacOS/Linux to load a font stored in your config directory. Windows might be trickier.

You could also detect the platform, and conditionally load a font that you like for each platform. You could use something like: `:lua print(vim.loop.os_uname().sysname)`
