### ISSUE TITLE
Guifont assignment from init.vim after upgrade

### ISSUE THREAD

**Issue by dvcrn** [equalsraf/neovim-qt#142]
I upgraded and recompiled with the latest master and have some trouble setting the font from within my init.vim

I have this snippet in my init.vim:
```
" Neovim-qt Guifont command
command -nargs=? Guifont call rpcnotify(0, 'Gui', 'SetFont', "<args>") | let g:Guifont="<args>"
:Guifont Hack:h14
```

which worked fine before but doesn't anymore. Every start resets the font to Courier New. 

Using `:Guifont Hack:h14` once the editor is started is setting the font just fine.

Did something change to this command?

**Comment by equalsraf** [comment]
Yes, a while back the command changed.

1. You should no longer need the 'command' definition in init.vim (there are still a few issue to be fixed in #127 let me know if the command is not available)
2. Move calls to GuiFont to ginit.vim instead of init.vim
3. Both `Guifont` and `GuiFont` should work, the later is preferred
