### ISSUE TITLE
The shim is not loaded soon enough

### ISSUE THREAD

**Issue by suy** [equalsraf/neovim-qt#156]
I've tried to install [a plugin for a different GUI](https://github.com/rhysd/nyaovim-popup-tooltip) to see if I could implement the GUI-side feature in Neovim-Qt, and understand a bit more the whole architecture. I've tried to fix the loading condition (before the `finish`) to check for `g:GuiLoaded`. It didn't work, and it is because the shim is loaded too late.

I did look at the code, and even if the command line arguments trick seems ugly (is there something better on the works on the server side?), to me that is supposed to work. The runtimepath is modified before the vimrc, so I don't what what's wrong. The shim is loaded in position 150, while the plugins are loaded before. Here is the order of `scriptnames` after plain startup: https://gist.github.com/suy/970fea1211ba01de57876a29f7c8035b

So, is there some fiddling with pathogen or the vimrc files that I'm not doing properly? My `init.vim` is a symbolic link to `vimrc`, and `ginit.vim` just contains a `GuiFont` command.

Thanks!

**Comment by equalsraf** [comment]
I don't think changing the runtime path alone can force the plugin to load. The GUI itself only tries to ensure the shim is loaded before sourcing ginit.vim.

https://github.com/equalsraf/neovim-qt/blob/5fef216796278e20a91db19b2330a582beac19cd/src/gui/shell.cpp#L137

> I did look at the code, and even if the command line arguments trick seems ugly (is there something better on the works on the server side?),

not right now, any further changes in this well need to go upstream first to handle the whole GUI initialization issue.

> So, is there some fiddling with pathogen or the vimrc files that I'm not doing properly?

You can try the following two options. First add the shim explicitly as a plugin (e.g. plugged) and load it earlier

```Vim
Plug 'equalsraf/neovim-gui-shim'
```

If you are chaging the nyaovim-popup-tooltip plugin, another option that seems generally more acceptable is to add a ginit.vim file to the plugin, that file should be sourced by the GUI after the shim too (because of the call to [runtime](https://github.com/equalsraf/neovim-qt/blob/5fef216796278e20a91db19b2330a582beac19cd/src/gui/shell.cpp#L138)).

**Comment by suy** [comment]
Closed in favor of an upstream solution, as mentioned in #158.
