### ISSUE TITLE
Neovim-Qt sometimes starts with small window

### ISSUE THREAD

**Issue by xelra** [equalsraf/neovim-qt#251]
This might be specific to Windows.

Sometimes the Neovim-Qt window is really small after starting it. It's hard to predict when it will happen, but it's more likely to happen on the first startup after a reboot. It never happens for consecutive startups.

This is how it looks:
![untitled](https://cloud.githubusercontent.com/assets/908568/23633629/cb3fe4d6-02c6-11e7-9b49-c02a50cc6c0f.jpg)

Then I just close the window and start Neovim-Qt again:
![untitled2](https://cloud.githubusercontent.com/assets/908568/23633687/011da69c-02c7-11e7-9221-e525762afe2f.jpg)

**Comment by equalsraf** [comment]
I can confirm this, we just discussed it in https://www.reddit.com/r/neovim/comments/5xm887/neovimqt_wont_read_my_configuration_files/

No idea what is going on there, the default behaviour should be to set the window to about 2/3 of the widht/height. But it sometime gets a lot smaller.

**Comment by christianrondeau** [comment]
Same issue: Windows 10 v1607, neovim v0.2.0.855 64 bit, nvim-qt v0.2.6... I think :) I actually don't know how to see the version number of nvim-qt!

**Comment by qwfy** [comment]
Having invalid settings in `init.vim` can cause this (tiny window), try typing `nvim-qt` in bash (instead of launching it from a icon) to see if any errors are printed.

**Comment by feanor12** [comment]
I have the same problem using arch-linux
starting nvim-qt from command line doe snot show any errors.
I think it happens when the content is not loaded fast enough.
For example when using a sftp mount.

**Comment by j-silver** [comment]
It's possible to impose the window size through the command line flag _--geometry (width)x(height)_ 

For example
$ nvim-qt --geometry 1400x900

I've defined an alias of nvim-qt in my .bashrc

**Comment by qwfy** [comment]
@feanor12 I made a mistake in my previous comment, typing `nvim` instead of `nvim-qt` in the command line, I've corrected it.

**Comment by feanor12** [comment]
@qwfy `nvim` does not create any errors on the command line, either.

**Comment by dumblob** [comment]
I experince very similar issue as @xelra. On my Windows 10 machine (freshly installed and updated) `nvim` always starts with a tiny window as @xelra showed disregarding whether it's a first execution or not after startup and disregarding whether it's plain execution from using a double click directly on the bundled `nvim-qt.exe` file or whether it's executed by Windows 10 when clicking on a text file associated (based on the file extension - you know the Windows way of handling "mime types") with `nvim-qt.exe`.

**Comment by DaSea** [comment]
In `ginit.vim` file, add `call rpcnotify(0, 'Gui', 'WindowMaximized', 1)`, can show maximized!

**Comment by RedX2501** [comment]
In my case it was an `echom` command in my `init.vim` file that prevented the window from reaching its size.

**Comment by davclark** [comment]
I have the same issue. Seems more common when I have an external monitor (in my case I have a different ratio for enlarging applications for hiDPI)

**Comment by tistatos** [comment]
I've had similar issue when on windows 10. My issue seemed to be plugins that had unmet requirement in regards to what flags nvim was compiled with. By disabling the plugins, the window opens in a proper size.

**Comment by kylemacfarlane** [comment]
I had the same problem and it ended up being caused by the YouCompleteMe plugin which wasn't starting up properly because I hadn't configured the Python provider yet.

But this bug is actually probably a symptom of another bug related to startup error messages. It's easy to recreate by doing something simple like setting `colorscheme` to something bad. `nvim-qt.exe` will start up with a tiny window (and broken colours of course) but no error messages. On the other hand `nvim.exe` will show the error messages but fail to start and has to be killed.

**Comment by shlomif** [comment]
I'm running into this problem here on Mageia Linux v7 using the Plasma 5 desktop and latest nvim and nvim-qt. I can reproduce it all the time by issuing `nvim-qt +mak` .

**Comment by luzhlon** [comment]
hey,  I have a temporary solution as follows

```viml
if !has('nvim') | finish | endif

fun! s:set_size(...)
py3 << EOF
from ctypes import *
u32 = WinDLL('user32.dll')

# Fix me
LEFT = 160
TOP = 50
WIDTH = 888
HEIGHT = 666

GetForegroundWindow = u32.GetForegroundWindow
GetSystemMetrics = u32.GetSystemMetrics
SetWindowPos = u32.SetWindowPos

cw = GetForegroundWindow()
SetWindowPos(cw, 0, LEFT, TOP, WIDTH, HEIGHT, 0)
EOF
endf

fun! s:start()
    " call timer_start(50, funcref('s:set_size'))
    call s:set_size()
endf

au GUIEnter * call <sid>start()
```

**Comment by equalsraf** [comment]
:o `GUIEnter` should not even be called in nvim. @luzhlon is s:start() getting called?

**Comment by luzhlon** [comment]
@equalsraf  thanks.
I added `doautocmd GUIEnter` in my ginit.vim 😀

**Comment by equalsraf** [comment]
Was it working before? It might just work as a side effect of waiting for the python provider to load.

**Comment by kierun** [comment]
I get the exact same problem but only calling `neovim-qt <some file>` and only on Windows.

**Comment by sryze** [comment]
I'm new to nvim-qt, I added `--maximized` to `nvim-qt.desktop` in order to have it start always maximized but sometimes the window appears small after startup and looks like it's chopped off (can't see what commands I'm typing):

![screenshot from 2017-12-24 09-33-51](https://user-images.githubusercontent.com/4525736/34324073-afa80fde-e88d-11e7-904c-3c321135f9c5.png)

**Comment by AdnoC** [comment]
Modified the code @luzhlon posted to correctly center windows on different resolution monitors and to also scale the size based on the resolution.

The code is rather large [so I put it in a gist](https://gist.github.com/AdnoC/bbbb7904f9ef1322c02a9d675e38634e).

**Comment by luzhlon** [comment]
@AdnoC  It's too complicated, but it is more perfect as well.

**Comment by AdnoC** [comment]
@luzhlon True enough. Removing the pid stuff and just grabbing the foreground window [makes it a bit more reasonable](https://gist.github.com/AdnoC/163f65e8df284ca52626e4dfcb7d8766).

Problem was that I opened vim and clicked something else while it was opening, which caused that thing's window to be resized instead of nvim's.

**Comment by Himura2la** [comment]
On Windows 10 you should use `-qwindowgeometry 800x600`

**Comment by tigerwin2015** [comment]
you can create a shortcut for nvim-qt.vim and change the target to something like `C:\tools\neovim\Neovim\bin\nvim-qt.exe -qwindowgeometry 1030x608` thanks to @Himura2la

**Comment by eyalk5** [comment]
`/Applications/nvim-qt.app/Contents/MacOS/nvim-qt --qwindowgeometry 6x4 ` opens it on maximum

**Comment by jgehrig** [comment]
We now store the window size on close, and restore on open.

This issue should not occur anymore. Marking as closed.

**Comment by roysubs** [comment]
This issue is constant when running in Windows Sandbox (which I use a lot for testing and development). I do not see this issue anywhere else. Can you see from the work on the fix above a way to fix the "tiny-window glitch" for neovim running in a Windows Sandbox container?

**Comment by ivankra** [comment]
Hey, this problem still affects me with latest nvim-qt 0.2.20 on Linux/X11 and seems to be triggered by display resolution changes.

I let Claude investigate and it claims the bug is here due to ignoring a potentially failing `QWidget::restoreGeometry()`: https://github.com/equalsraf/neovim-qt/blob/afd6f56219d2c5cd873252b76d4bd608303a3d6a/src/gui/mainwindow.cpp#L350

Qt6 has some misbehaving sanity check that can cause `QWidget::restoreGeometry()` to fail on large resolution swings
https://code.qt.io/cgit/qt/qtbase.git/tree/src/widgets/kernel/qwidget.cpp#n7550
