### ISSUE TITLE
Trying to build on linux

### ISSUE THREAD

**Issue by Astara** [equalsraf/neovim-qt#263]
I don't think anyone ever tried the unix example:
mkdir build
cd build
> cmake -DCMAKE_BUILD_TYPE=Release
CMake Error: The source directory "/home/tools/vim/neovim-qt/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
----
Tried to build from dir above:
> cmake -DCMAKE_BUILD_TYPE=Release
CMake Error: The source directory "/home/tools/vim/neovim-qt/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Ishtar:tools/vim/neovim-qt/build> cd ..
Ishtar:tools/vim/neovim-qt> cmake -DCMAKE_BUILD_TYPE=Release
CMake Error at CMakeLists.txt:36 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "/home/tools/vim/neovim-qt/CMakeFiles/CMakeOutput.log".

Thought maybe it needed qt5 installed... so installed that, but it had no cmake filse or widgets
So I have no idea what to st qt5 widgets to or how to use cmake.  

So where do I get the needed files?

Maybe this could be fixed in the building instructions?

thanks!
linda

**Comment by equalsraf** [comment]
The qt5 packages should already provide this. Usually in the -devel packages, but this will vary with your linux distribution.

For example in my system the qt5-devel package has those files. What distribution are you using?

**Comment by suy** [comment]
> Maybe this could be fixed in the building instructions?

The build instructions say `cmake -DCMAKE_BUILD_TYPE=Release ..`. The dots at the end are important. And yes, you are missing Qt, at least, the parts needed to build, as equalsraf said.

**Comment by Astara** [comment]
@equalsraf wrote:
>
> The qt5 packages should already provide this. Usually in the -devel 
> packages, but this will vary with your linux distribution.
>
> For example in my system the qt5-devel package has those files. What 
> distribution are you using?
>
---
    I installed qt5 from the qt5 website using their
installer: qt-unified-linux-x64-2.0.5-2-online.run

    I thought they might have the latest and most complete
version, but perhaps their installer is broken/doesn't install
everything.

    Hmm...looking at my distro's packages, I see:
>  ls /suse132/*qt5*|wc -l
261
>  ls /suse132/*qt5*|grep devel|wc -l
114

261 packages with 114 devel packages. 

So too bad the qt-installer is junk... (sigh)...
Will have to figure out a way to whittle down that list
to what is needed...

**Comment by Astara** [comment]
Alejandro Exojo wrote:
>
>     Maybe this could be fixed in the building instructions?
>
> The build instructions say |cmake -DCMAKE_BUILD_TYPE=Release ..|.[sic]
> The dots at the end are important. And yes, you are missing Qt, at 
> least, the parts needed to build, as equalsraf said.
>
---
    Then those aren't very complete instructions, and to be literal,
the example has "..",  not an ellipses.  ".." is a valid
path and looks like an argument to cmake, which tells it to look
in the parent dir for files (which also didn't work).

    Cmake (based on a windows build util pcmaker.exe), isn't
universally known by linux/unix users where the cryptic 'configure'
has been a standard for over a decade.

When one uses 'configure' to configure a linux build, the just
type "configure" --- nothing else.  No dots.

It can be modified to suit my tastes, but getting a basic and
default build to work doesn't take a vague "fill in the dots"...

That's been a problem with cmake examples for linux, as no one
seems to know (or want to list) what those dots are, whereas
the general "config-for-all-platforms ("all" keeps expanding),
doesn't require someone to "just know" what is needed for a tool
they've never used.

That's why I asked for a more complete/detailed invocation, since
the old-standard "configure" was brain-dead simple.

Then it really would be something that one
    "can build using CMake and your build system of choice".

But most linux/unix users won't know how to use that.

*cheers*...

**Comment by equalsraf** [comment]
> I installed qt5 from the qt5 website using their installer: qt-unified-linux-x64-2.0.5-2-online.run

Ok that explains it to some extent. CMake is a third party tool and it seems the installer does not setup the environment to address this (the Qt [docs](http://doc.qt.io/qt-5/cmake-manual.html) briefly mention the setup). It seems likely cmake would be unable to find Qt unless its in the PATH but I will have to take a look at this later. This definitely does not occur in regular distro packages or in the windows installer.

@Astara its been a while since I've used suse. I believe zypper does provide options to figure out the package that owns a file.

The pkg for the files you pointed out in suse is libQt5Widgets-devel, but likely you want to install all the development files from libqt5-qtbase. 

> That's why I asked for a more complete/detailed invocation, since the old-standard "configure" was brain-dead simple.

The `..` is the parent path. Or rather the path to the source (where CMakeLists.txt is located). This is intended for out-of-source builds, where the binaries are placed away from from the source code. But in fact you could do a `cmake .` in the source directory.

Since cmake is basically a meta build system it produces as output a valid build file for some other build system - in unix the default is usually make (unless it is not available).

Thanks for taking the time to report here. I'll have a look at updating the README.

> where the cryptic 'configure' has been a standard for over a decade.

This made me smile :D I'm pretty sure its been far more than a decade.

**Comment by Astara** [comment]
@equalsraf wrote:
>
> @Astara <https://github.com/Astara> its been a while since I've used 
> suse. I believe zypper does provide options to figure out the package 
> that owns a file.
>
----
    If they are installed, yes, but not when they are still in random
directory.  FWIW, though, I've dumped out filelists from all the
rpms in the current version I have installed (as well as having all
those packages already downloaded), so I can just do a "grep -r" on
filename & base dir.
>
> The |..| is the parent path. Or rather the path to the source (where 
> CMakeLists.txt is located). This is intended for out-of-source builds, 
> where the binaries are placed away from from the source code. But in 
> fact you could do a |cmake .| in the source directory.
>
---
    Yeah... apparently Alijandro Exojo didn't know that, offhand, either,
as he "corrected[sic]" it to an ellipses, saying I was supposed to fill
that in...
>
> Since cmake is basically a meta build system it produces as output a 
> valid build file for some other build system - in unix the default is 
> usually make (unless it is not available).
>
> Thanks for taking the time to report here. I'll have a look at 
> updating the README.
>
>     where the cryptic 'configure' has been a standard for over a decade.
>
> This made me smile :D I'm pretty sure its been far more than a decade.
>
----
    I was being conservative, though you're very likely right.

Ok.. just installed all the devel files that would install w/the libs
I have installed, this looks better:

Ishtar:tools/vim/neovim-qt/build> cmake -G'Unix Makefiles' ..
-- Downloading Msgpack...
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR 
GTEST_MAIN_LIBRARY)
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.8")
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE 
-- Performing Test MSGPACK_ENABLE_GCC_CXX_ATOMIC
-- Performing Test MSGPACK_ENABLE_GCC_CXX_ATOMIC - Failed
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.8")
-- Found PythonInterp: /usr/local/bin/python (found version "2.7.8")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tools/vim/neovim-qt

So do I need GTEST?

Interesting that it automatically downloaded msgpck,
though..
any idea why MGGPACK_ENABLE_GCC_CXX_ATOMIC would fail?

Since I recently built my own gcc from 6.0 sources (my
distro only had 4.something for 13.2), it might have
something to do with my options or using a newer gcc than
expected(?) ...

FWIW, I build several packages directly from downloaded
source tarballs or source-control-trees (git, or whatever)...
some recent ones: gcc, squid, iputils, bash, util-linux,
transmission, coreutils, ethtool, file, samba
and the linux kernel.

It's not that my distro doesn't include some version of them,
but that I either use different versions (usually more recent),
different options, or different optimizations.

Thanks for your time and not being a butt.  ;-)

**Comment by suy** [comment]
>     I installed qt5 from the qt5 website using their
> installer: qt-unified-linux-x64-2.0.5-2-online.run
> 
>     I thought they might have the latest and most complete
> version, but perhaps their installer is broken/doesn't install
> everything.

It is not broken and it installs everything needed, in a simpler way that most 
distribution packages, because it doesn't split much the packages (specially 
it doesn't split the headers because it's expected that users of the 
installers are all of them going to compile something).

> 
> So too bad the qt-installer is junk... (sigh)...

It is not junk, your attitude, on the other hand...

> > The build instructions say |cmake -DCMAKE_BUILD_TYPE=Release ..|.[sic]
> > The dots at the end are important. And yes, you are missing Qt, at
> > least, the parts needed to build, as equalsraf said.
> 
> ---
>     Then those aren't very complete instructions, and to be literal,
> the example has "..",  not an ellipses.  ".." is a valid

I typed exactly the instructions on the readme, and the quoted part, given 
that it's code, was wrapped in back-ticks. You can still check the comment and 
see that is boxed and in a different font. The last point was the end of the 
sentence.

> path and looks like an argument to cmake, which tells it to look
> in the parent dir for files (which also didn't work).

Because those are a general instruction for a general case. Yes, if you don't 
have the necessary files in the assumed paths things will change.

What you are looking for here is setting CMAKE_PREFIX_PATH.

https://blogs.kde.org/2008/12/12/how-get-cmake-find-what-you-want-it

>     Cmake (based on a windows build util pcmaker.exe), isn't
> universally known by linux/unix users where the cryptic 'configure'
> has been a standard for over a decade.

Autotools is not universally known either, because people who started using 
Linux recently have barely been exposed to it because its clear decadence.

> When one uses 'configure' to configure a linux build, the just
> type "configure" --- nothing else.  No dots.

All builds that can be done with one naked call to configure can be done with 
a naked call to cmake. The instructions just hint at using a build out of 
source, because it's the clean thing to do. How do you do that with configure? 
Surprise: `../source-dir/configure`. Wow. So different to `cmake ../source-
dir`.

And an autotools based build would fail exactly in the same way. How is the 
build going to figure out _where_ did you install Qt if it's in a non-standard 
path?

> It can be modified to suit my tastes, but getting a basic and
> default build to work doesn't take a vague "fill in the dots"...
> 
> That's been a problem with cmake examples for linux, as no one
> seems to know (or want to list) what those dots are, whereas
> the general "config-for-all-platforms ("all" keeps expanding),
> doesn't require someone to "just know" what is needed for a tool
> they've never used.
> 
> That's why I asked for a more complete/detailed invocation, since
> the old-standard "configure" was brain-dead simple.
> 
> Then it really would be something that one
>     "can build using CMake and your build system of choice".
> 
> But most linux/unix users won't know how to use that.

More and more non-sense. CMake it's the most popular build system for C and 
C++ projects nowadays.

And I *hate* cmake. The command line arguments are annoying to type because 
are very verbose. And the cmake language... don't get me started. But your 
comments so wrong, that I had to "defend" it, because I hate more not telling 
the truth.

It's fine that you ask for help because you don't know cmake. I've been there 
most of the time because I don't like it at all, so I refused to learn it. But 
don't criticize other's work unfairly please. The README is fine. CMake is 
fine. The Qt installer is fine. You didn't get all set up in the first place 
because things are not so simple, but you are getting help.

**Comment by suy** [comment]
On Tuesday 11 April 2017 14:54:12 Astara wrote:
>     Yeah... apparently Alijandro Exojo didn't know that, offhand, either,
> as he "corrected[sic]" it to an ellipses, saying I was supposed to fill
> that in...

I did not correct a thing. Check the messages. Or the website. Does it say 
that I edited it?

And when did I say that you had to fill that in?
 
> Thanks for your time and not being a butt.  ;-)

Now you are not only incorrect, but you lie, and insult me. You are certainly 
making progress in the right direction.

**Comment by equalsraf** [comment]
> So do I need GTEST?

No. The GTEST message is non fatal - its msgpack warning that it did not find gtest for its tests - but thats ok, after all its an optional dependency of a dependency. Not much I can do to remove the message, but otherwise its harmless.

> Interesting that it automatically downloaded msgpck, though..

That was our doing actually - when neovim started there were several distros where msgpack was not available - so neovim builds it statically, and so do we.

If you have a libmsgpack in your system and you want to use it pass the following option to cmake `-DUSE_SYSTEM_MSGPACK=ON`. It will skip the download for msgpack and try to find a shared library for it in your system.

> any idea why MGGPACK_ENABLE_GCC_CXX_ATOMIC would fail?

No idea, but to be fair we dont even link against the C++ msgpack lib, we just use its C api. In case you are interested that particular message relates to the following check in the msgpack code 

```cmake
CHECK_CXX_SOURCE_COMPILES ("
#include <bits/atomicity.h>
int atomic_sub(int i) { return __gnu_cxx::__exchange_and_add(&i, -1) - 1; }
int atomic_add(int i) { return __gnu_cxx::__exchange_and_add(&i, 1) + 1; }
int main(int argc, char * argv[])
{
    atomic_sub(1);
    atomic_add(1);
}
" MSGPACK_ENABLE_GCC_CXX_ATOMIC)
```

It is actually succeeding in my gcc (6.3)

> -- Build files have been written to: /home/tools/vim/neovim-qt

The cmake step seems to have succeded or at least I dont see any fatal error messages in your log. Have you tried to run make/make install?

For completeness on cmake its important to point out that:

- if you want to change the target install dir (i.e. --prefix) use `cmake -DCMAKE_INSTALL_PREFIX=/usr ..`
- If you see that calling `cmake -Doption` is not producing any change you might want to remove the build dir and start over - it should no be the case for the install prefix, but it might happen that it does not pick up on the dependency changes.

**Comment by Astara** [comment]
Alejandro Exojo wrote:
> On Tuesday 11 April 2017 14:54:12 Astara wrote:
> > Yeah... apparently Alijandro Exojo didn't know that, offhand, either,
> > as he "corrected[sic]" it to an ellipses, saying I was supposed to fill
> > that in...
>
> I did not correct a thing. Check the messages. Or the website. Does it 
> say
> that I edited it?
---
    I just got an email message from you in text that Looks like
this:

The build instructions say |cmake -DCMAKE_BUILD_TYPE=Release ..|. The 
dots at the end are important. And yes, you are missing Qt, at least, 
the parts needed to build, as equalsraf said.

>
> And when did I say that you had to fill that in?
---
    When you said the dots at the end (that look like an
ellipses (…) in email) are important, it was read by me as
you saying that the "rest of the statement" (the ellipses part)

    Given the ambiguity of a bare ".." looking like multiple thing
(and especially being further confusing when followed by a period),
maybe something like
./..
or
../.
and a space before any period would better alleviate ambiguity?
>
> > Thanks for your time and not being a butt. ;-)
>
> Now you are not only incorrect, but you lie, and insult me.
----  
    Hmmm... So you were being a butt?  And my saying that you
were not being a "butt" was your idea of an insult? 
Um...<tone="sarcasm"> no, no confusion here, not a chance,
right. </tone>  (Just making it clear, given the crossed signals
in play). 

     HOWEVER:
    FWIW, I was responding to @equals...
> You are certainly
> making progress in the right direction.
---
    Given the misunderstandings and your feeling insulted, I'm
not sure if that is sarcasm or not.

P.s. ignoring your previous post, since to respond to various items
that were based on misunderstandings, would only likely cause further
misunderstandings...

Though 1 point,  you said:

More and more non-sense. CMake it's the most popular build system for C and
C++ projects nowadays.
----
    *Maybe* c++, as I haven't seen enough of them to be sure... most
I have seen still use configure+make.  But 'C'? none of the C-projects I
build use Cmake.   FWIW, this is the 2nd project I've been interested
in building, that has used Cmake (first was doxygen, which in earlier
versions used configure).  Even there, when others asked how to use
cmake in the doxygen forums -- they were ignored
(https://sourceforge.net/p/doxygen/mailman/message/34246818/).

**Comment by Astara** [comment]
@equalsraf wrote:
>
>     Re: GTEST needed?
>
> No. … Not much I can do to remove the message, but otherwise its harmless.
>
that's fine…
>
>     Interesting that it automatically downloaded msgpck, though..
>
> That was our doing actually - when neovim started there were several 
> distros where msgpack was not available - so neovim builds it 
> statically, and so do we.
>
---
fine too... you don't necessary know that my installed version would
work for you, anyway...I had an old version of it from 2015, but who
knows if that would have worked...(just wiped it)...

> No idea, but to be fair we dont even link against the C++ msgpack lib, 
> we just use its C api.
>
----
    Again… fine … didn't know.
>
> It is actually succeeding in my gcc (6.3)
>
oops: > gcc --version
gcc (GCC) 6.3.0
---
    (just d/l'd it -- was latest released version...
considering my distro's 13.2 (now considered obsolete) only had 4.x,
I only was looking at major Ver.)

>     -- Build files have been written to: /home/tools/vim/neovim-qt
>
> The cmake step seems to have succeded or at least I dont see any fatal 
> error messages in your log. Have you tried to run make/make install?
>
---
    Yes... and this was confusing -- it failed not finding "nvim"...
I see from the instructions it was supposed to be in my path.

    Is nvim==neovim?  Isn't that what I'm building (except the qt5 version?)

    Isn't that like saying 'gvim' or 'vim' needed to be in my path? 
I.e. why do I need a gui-editor (or nvim in particular) in my path?
Confused?

**Comment by equalsraf** [comment]
> considering my distro's 13.2 (now considered obsolete) only had 4.x, I only was looking at major Ver.)

Another wild guess that comes to mind on this is that somehow there is something wrong with your libstdc++ or your headers.

> Is nvim==neovim? Isn't that what I'm building (except the qt5 version?)

`nvim` is the neovim binary.  But this repository only hosts a GUI for neovim it still requires neovim to be installed.

Unlike in vim where `vim` and `gvim` are just different versions of the vim binary (one which happens to spawn a GUI) in neovim the GUI is a completely separate program that talks to the nvim binary.

There are other GUIs for neovim, here is the full [https://github.com/neovim/neovim/wiki/Related-projects#gui] from the neovim wiki.

**Comment by Astara** [comment]
@equalsraf wrote:
>
>     considering my distro's 13.2 (now considered obsolete) only had
>     4.x, I only was looking at major Ver.)
>
> Another wild guess that comes to mind on this is that somehow there is 
> something wrong with your libstdc++ or your headers.
>
---
    Only error in build was missing neovim -- so need to build that
next -- didn't quite get that neovim was a base that provides
its functionality via rpc (thus the need for msgpack I'm assuming)...

    FWIW, gcc includes libstdc and libstdc++ because their format
depends on the compiler, so building gcc (& g++) gets me the libs...
(theoretically).  Using my own gcc is new (~1 week), so still not
sure how reliable it is ....

    That brings up an interesting possibility that may be completely
unnecessary, but occurred, nevertheless.

    Is it possible to run neovim on one machine and the gui on another?

    I do most of my work logged-in remotely and use gvim, for instance,
via 'X'.  Likely not much of a difference, but I'd still bet msgpack
is more efficient than X...   Anyway, just a thought...probably more
work than its worth.

**Comment by equalsraf** [comment]
> neovim was a base that provides its functionality via rpc (thus the need for msgpack I'm assuming)...

Correct msgpack-rpc is the protocol used to invoke neovim's remote api.

> Is it possible to run neovim on one machine and the gui on another?

Yes. it is possible and you can also leave neovim running in the background in one machine and reatach when needed.

I've seen a couple different setups for this lying around. For example a quick hack using ssh as the communication channel is this

    nvim-qt --nofork --spawn ssh hostname nvim

But this is not ideal because
- if the connection dies, so does the nvim process
- you may run into issues with ssh prompting for a password (which is why I added the `--nofork` above).
- if you take too long to authenticate to ssh the GUI might timeout the connection, but it should provide a retry button

The `--spawn ssh hostname nvim` orders the GUI to call `ssh hostname nvim ...(other arguments)` instead of 'nvim ...(other arguments)'. Other forms are also available e.g. `nvim-qt --server 127.0.0.1:8888` uses a TCP socket, but a path to a UNIX socket is also acceptable.

A more reliable way to do it is to have nvim running in the background on the remote machine and setup its listening socket in a known location and then setup ssh to forward it (both TCP or UNIX sockets work).

Usually the main annoyance when doing this is system clipboard integration - because the clipboard in neovim works differently it would not be forwarded. There are a couple open issues upstream to solve this.
