### ISSUE TITLE
Strange ui output on windows

### ISSUE THREAD

**Issue by skywind3000** [equalsraf/neovim-qt#304]
Operating System: windows
binary build: a prebuild version download from neovim's release page (neovim is 0.2.1)

reproduce:

```VimL
:silent !start cmd.exe /C dir & pause
```

before running the command:

![nvim-qt-1](https://user-images.githubusercontent.com/3035071/27781861-96850d04-6002-11e7-946f-9634421a215d.png)

after running the command:

![nvim-qt-2](https://user-images.githubusercontent.com/3035071/27781880-aa542fa4-6002-11e7-84b6-83abac5dd63e.png)

1. strange output in the cmdline area
2. tabline disappeared.

**Comment by equalsraf** [comment]
Very strange. Does it eventually get back to normal - e.g. if you `:redraw`?

**Comment by skywind3000** [comment]
GUI restored after `:redraw!`,
But I am afraid there is an important bug like access an invalid memory area....

**Comment by equalsraf** [comment]
Possible, but first we need to figure out if the issue is in the GUI or in Neovim. Usually the GUI just renders what nvim tells it.

It seems more likely that `start` is producing output that somehow causes that breakage in the display.

The disappearing tabline is not unexpected as the interface scrolls to show the command output. The issue here is the displayed text.

Does this also happen with other commands? like `!echo hello`

**Comment by DustinVenegas** [comment]
neovim/neovim#5844 directly relates to this issue. 

neovim-qt is fine. Neovim has issues parsing un-quoted parameters. I can definitely reproduce this in Windows using nvim 0.2.2. 

Quoting the parameters to `cmd.exe` is a current workaround.

```viml
:silent !start cmd.exe "/C dir & pause"
```

**Comment by justinmk** [comment]
@DustinVenegas Nvim prerelease (0.3.0) has some improvement with quoting on Windows, e.g. https://github.com/neovim/neovim/pull/7343

**Comment by janlazo** [comment]
```vim
silent !start cmd.exe /c dir & pause
```

runs `cmd.exe /c dir` in a different window and runs `pause` after `start`. `start <command> & pause` where `<command>` is `cmd.exe /c dir`.
neovim/neovim#7343 doesn't affect that behaviour but @DustinVenegas workaround doesn't work now, because it doesn't work in a cmd.exe prompt.

I'd change that to `silent !start cmd.exe /s/c "dir & pause"` to mirror nvim's behaviour but `/s` is optional for this specific command.
