### ISSUE TITLE
Command - T doesn't work on neovim-qt but works on neovim

### ISSUE THREAD

**Issue by fakeid30** [equalsraf/neovim-qt#318]
So, I installed Command-T , the gem(neovim) and added environment variable to my .zshrc , But I can't use the plugin from inside Neovim-qt , it complains in :CheckHealth that gem neovim is not installed. 

I have the plugin fully working on terminal nvim though. So I can't figure out what's wrong. 

Arch Linux, installed using this: https://aur.archlinux.org/packages/neovim-qt-git/

Relevant .zshrc : 
```
if which ruby >/dev/null && which gem >/dev/null; then
    PATH="$(ruby -rubygems -e 'puts Gem.user_dir')/bin:$PATH"
fi
```

**Comment by equalsraf** [comment]
Some questions to clarify whats going on:

1. You set PATH in .zshrc to include a rubygem path (I assume this is needed because of a helper), What does "$(ruby -rubygems -e 'puts Gem.user_dir') evaluate to?
1. in nvim-qt does  `:echo $PATH` show the the rubygem path?
1. Are you calling nvim-qt from a terminal or from a launcher/menu - try from a console.

I'm assuming the PATH is not set correctly in nvim-qt, because .zshrc was never evaluated by the process that called it, because it was not the shell (or it was a login shell).  If you move that configuration to `~/.profile` does it work?

**Comment by equalsraf** [comment]
Ah appologies, I'm unfamiliar with zsh configuration files, perhaps it should go into .zshenv instead.

**Comment by fakeid30** [comment]
Moving the configuration to ~/.profile worked, thanks !
