### ISSUE TITLE
Neovim is not responding try again

### ISSUE THREAD

**Issue by iamkarlson** [equalsraf/neovim-qt#319]
I've got this issue millions times and it really affects my experience of using neovim. How can I work around that without rebuilding anything from the scratch or without any other kind of complicated things? I suppose there's an issue with opening particular files with neovim or there's a timeout, I don't know. 

At least just give me please any idea how I can collect debug information of such issues.

**Comment by equalsraf** [comment]
This is usually caused by one of the following

1. nvim really is taking too long to startup - the current timeout is 5s, the best I can do for this is provide you with a way to increase this time.
2. nvim started up but some error happened, causing it to block (e.g. waiting for user input https://github.com/equalsraf/neovim-qt/issues/78)

What OS and nvim version are you using?

**Comment by iamkarlson** [comment]
I'm on nightly builds of neovim under windows 10 (last updates)

**Comment by iamkarlson** [comment]
So, the task which did you mention is two years old.  Is there still the same?

**Comment by justinmk** [comment]
>  the current timeout is 5s, the best I can do for this is provide you with a way to increase this time.

On my system after a reboot, initial startup can take longer than 5s. Might be good to bump it to 10s, to avoid false bug reports.

**Comment by iamkarlson** [comment]
And it won't help when neovim is waiting for input, am I right? Can we do
anything else with that?

**Comment by justinmk** [comment]
I have some ideas for that, working on it.

**Comment by iamkarlson** [comment]
@justinmk good to hear!! good luck!

**Comment by equalsraf** [comment]
For 1. I've merged #320 the timeout should now be 10s. If this is not enough `--timeout` can be used to specify higher values.

@iamkarlson appveyor is still building the windows binaries, if you are in a hurry the pr builds are [here](https://ci.appveyor.com/project/equalsraf/neovim-qt/build/1163), otherwise the staging build in the release page should be updated in a bit.

**Comment by iamkarlson** [comment]
@equalsraf great, I start using it now and look forward to @justinmk fix

**Comment by iamkarlson** [comment]
#322
