### ISSUE TITLE
Neovim-qt freezing after start external app

### ISSUE THREAD

**Issue by iamkarlson** [equalsraf/neovim-qt#324]
I'm starting external app through exclamation mark and silent.  This app returns me an error with a popup. This popup is not correctly handled by nvim-qt and that leads to hanging the whole app.

My command to run:

```   
:silent !start "c:\Program Files\ConEmu\ConEmu64.exe" -single -dir "%:p:h"
```

**Comment by equalsraf** [comment]
`!` does block nvim until the program exits.

In windows vim considered `!start` as being special. But in nvim it is just the same as calling start.exe. 

`!` itself is also different from vim in that it does not support interactive commands (:terminal can be used for interactive commands)

**Comment by equalsraf** [comment]
Longer version: there are differences in shell related commands in vim/nvim (!, system).

1. In vim these, have issues related to shell quoting. In nvim system() works around this using system([]) to skip the shell.
2. **!** in vim supports interactive commands, nvim does not (partially due to internal differences), and nvim has `:terminal` to compensate. 
3. `!start` holds no special meaning in nvim, its just `start.exe ...` as called using system('start ...')

In nvim non shell specific commands (system([...])) are usually prefered to the Vim compatible commands, because they avoid shell specific settings. The preferred way for a background process is to call `jobstart(['c:\...\conemu.exe'])`

In your case, calling start is probably calling something like `cmd /c start ...`. The strange bit in your issue is that some process seems to be blocking (I would suspect cmd.exe is still running). You can try with a different shell, e.g. powershell definitely works for me

```
set shell=powershell
!Start-Process "..."
```

For me calling `!start` with the default settings also has unexpected results

- `!start invalidcmd` blocks but fails, which is strange
- `!start ping` works
- `!start "ping"` just opens cmd.exe

So likely this is related to quoting with cmd.exe. BTW it is worth it to document this stuff and if necessary suggest different default settings upstream.
