### ISSUE TITLE
Possibility for scrollbars?

### ISSUE THREAD

**Issue by frankie-loves-jesus** [equalsraf/neovim-qt#326]
Hi! Any chance nvim-qt (Windows 10) can support a right scrollbar similar to gVim?

Many thanks!

> I know that I can use the mouse wheel, but a scroll bar provides much more feedback about document length and current location of the view related to the complete file.
> IMHO, this should be a priority feature.

Ref. Add GUI scroll bars (Mac OS X): https://github.com/rogual/neovim-dot-app/issues/294

**Comment by equalsraf** [comment]
I assume you were thinking about something similar to the gVim behaviour where two scrollbar layouts are placed at both sides of the window (:h gui-scrollbars).

Yeah this seems possible but it will be some work. We need two things

1. on this repo we need to change the gui shell to have space for the scrollbars. and build a scroll bar layout
2. a vim script (to be part of the gui shim) that keeps track of the windows, their sizes and the scrollbar position and reports this information to the gui. 
3. figure out the correct way to scroll a window using the neovim api

As a side note, I'm not a big fan of the Vim vertical scroll bar setup, because they stop being so convinient when you have more than 2 vertical splits. So if anyone has any other concepts.those would be welcome. This PR https://github.com/neovim/neovim/pull/6373 would likely make that possible.

**Comment by frankie-loves-jesus** [comment]
What I had in mind were vertical scrollbars only, but come to think of it horizontal ones would be friggin' sweet as well.

As for vertical splits I've never felt the need for them when I can just launch another Vim, but I can understand why you terminal-savvy users might want them.

Cheers!

**Comment by 3rdey3** [comment]
👍

**Comment by nash900** [comment]
Vertical scroll bar for Neovim is a nice feature. Hope to see this enhancement in future. Thanks.

**Comment by qwfy** [comment]
I think a scrollbar is an essential part of a text editor with a GUI.

Often, you just want to open a file and quickly scroll through it, surely you can do it with keyboard, but sometimes it's just more convenient to use a mouse. Keyboard is good for heavy editing and serious  navigation, but mouse has its use cases.

**Comment by hasufell** [comment]
neovim... 20+ attempts of GUI editors. Half of them abandoned/archived, the others missing basic GUI functionality ;)

**Comment by facundobatista** [comment]
Scroll bars are a "must" in my way of working. 

To explore a file they are mandatory, specially if the text is wider than the window, as moving with the keyboard will make the GUI to reposition according to each line length.

I hope this is implemented soon...

**Comment by jgehrig** [comment]
@facundobatista

See the Pull Request above, we're working on this! :)

Any testing/code review/debugging you can provide would be greatly appreciated. Give the patch a try, it is currently functional.

FYI, there are still a few scrollbar synchronization bugs I need to fix...

**Comment by facundobatista** [comment]
Thanks! I will follow this in #642

**Comment by jgehrig** [comment]
As of release `v0.2.16`, scrollbars are supported.

You can enable the scrollbar via `:GuiScrollBar 1`. See `:help GuiScrollBar`.

Marking this issue as closed.

**Comment by ggnicastro** [comment]
GuiScrollBar 1 only active vertical scroll bar, but it now active vertical scroll bar.
Is it possible to have vertical scroll bar?
