### ISSUE TITLE
Empty row in the bottom!

### ISSUE THREAD

**Issue by concatime** [equalsraf/neovim-qt#359]
Is it normal that I have an empty row at the end?
![error](https://user-images.githubusercontent.com/26262387/32859671-2820087a-ca1d-11e7-9b14-78766f23c2f6.png)
I'm currently using `neovim-qt-git` from AUR, inside sway (wayland), under VMware Worksatation Player 14. Here is my [`init.vim`](//github.com/concatime/dotfiles/blob/master/.config/nvim/init.vim).
`qmake --version`
```
QMake version 3.1
Using Qt version 5.9.2 in /usr/lib
```

**Comment by WolfgangMehner** [comment]
Did you set `cmdheight`:

    :set cmdheight?

**Comment by WolfgangMehner** [comment]
See also #352.

**Comment by concatime** [comment]
I did nothing on my side beyond installing and setting my init.vim.
`:set cmdheight?`: `cmdheight=1`

**Comment by jarias** [comment]
Same here, `cmdheight` does nothing

**Comment by equalsraf** [comment]
It seems the extra space at the bottom is not enough to for a new row https://github.com/equalsraf/neovim-qt/issues/352#issuecomment-344731803. As such the additional space goes under the cmdline.

If anyone has this issue where the space under the cmdline is taller than a single text row, please reopen.

**Comment by thomasahle** [comment]
I too get such a weird "blank line" in Terminal no Mac, though not in iTerm2.
Since the terminals are supposed to only resize to window sizes fitting with a given number of linies, it seems that Terminal somehow measures neovim incorrectly. This problems don't appear in normal vim.
Does neovim report it's required size for given numbers of lines to the terminal somehow?
I don't know what could be causing this problem, but it clearly isn't working as it should.

**Comment by manujchandra** [comment]
I am using Alacritty + NVIM and Sauce Code Pro nerdfont.

I have noticed that using certain font sizes like 14 or 12 makes the last line disappear. Using a font size of 13 makes it reappear.
