### ISSUE TITLE
GuiLinespace behavior with negative numbers

### ISSUE THREAD

**Issue by Leandros** [equalsraf/neovim-qt#370]
The, sort-of, sister issue to #369. 
After I figured out how to set negative linespacing numbers, I realized neovim-qt, as opposed to gvim, only subtracts the linespacing from the top, resulting in the linespacing only getting thin at the top of each line. This is usually fine for things like text, but once you have a line filled with a background (like a statusline), you notice it. 
I believe gvim is subtracting half the linespacing at the bottom and the other half at the top, to shrink the lines equally.

It would be terrific if this behavior could be fixed in neovim-qt. So far I'm very happy, looks and feels beautiful. Great work!

**Comment by equalsraf** [comment]
Not all GUIs have the same behaviour e.g. from https://github.com/equalsraf/neovim-qt/pull/127#issuecomment-221408496 for positive values we used to put space at the bottom, MacVim places it at the top

![](https://cloud.githubusercontent.com/assets/1681606/15520717/5cfb1fb4-2210-11e6-86d5-3ab67da3be53.png)

And it seems gvim splits the space between the top and bottom ([code here](https://github.com/vim/vim/blob/master/src/gui_gtk_x11.c#L5164))

![2018-01-20-232144_916x558_scrot](https://user-images.githubusercontent.com/715238/35188957-c93059e6-fe38-11e7-8a2d-f7337d55d7b2.png)


So basicaly linespace

1. alters the line height ([here](https://github.com/equalsraf/neovim-qt/blob/master/src/gui/shellwidget/shellwidget.cpp#L95))
2. changes the baseline of the text being drawn ([here](https://github.com/equalsraf/neovim-qt/blob/master/src/gui/shellwidget/shellwidget.cpp#L158)) pushing it down for positive values

I don't mind either way, but this is one of those that usually falls under personal preference.

Some quick side notes for later

- what happens when linespace is an odd number/2 we dont deal with floating point coordinates
- did some testing with negative linespace, if we use a very low number we seem draw text over the previous line, probably need to clip it

**Comment by justinmk** [comment]
FWIW I just noticed that nvim 0.2.3 doesn't forward the 'linespace' option. https://github.com/neovim/neovim/pull/7883 corrects that.

**Comment by Leandros** [comment]
Would be great to have neovim-qt behave similar to how gvim does behave (or, alternatively, change the behavior with a config option).
