### ISSUE TITLE
Loading environment variables from bashrc

### ISSUE THREAD

**Issue by haadr** [equalsraf/neovim-qt#407]
Hi all and thanks for neovim-qt!

In my normal nvim setup, I often use environment variables defined in my .bashrc to quickly navigate to various folder and projects. It doesn't seem like these get imported automatically in neovim-qt, though you can kind of manually source the .bashrc file. 

Are there any plans/does it make sense for neovim-qt to import these so that theyre available as they are when launching nvim in a terminal? For that matter, gvim also seems to import them.

**Comment by equalsraf** [comment]
I'm probably missing something about your setup. The shell should already handle this for you.

- :terminal starts the shell, so it should load .bashrc
- When using command mode `:` the environment should also be available if nvim-qt was started by your shell. If you are starting from a menu/launcher then this might depend on your window manager.

Are you by chance using Mac OS X and starting neovim-qt from the dock? In that particular case we do attempt to load your shell environment.

**Comment by haadr** [comment]
Well I'll be damned!

I must have launched gvim from some kind of shell before, so that my environment variables were loaded by it, but launched nvim-qt from plasmashell directly. 

You are correct, when I launch nvim-qt from a terminal, the environment variables all get loaded. When I launch it via krunner (plasma), they don't. 

Sorry for the confusion! I thought the loading was done by gvim itself, not the launching process.

**Comment by equalsraf** [comment]
We do have a workaround for this kind of thing, but it is only enabled for Mac OS X (code [here](https://github.com/equalsraf/neovim-qt/blob/master/src/gui/app.cpp#L56)) maybe we can try and turn it into a flag of sorts.

Another alternative is to change the .desktop to work around this (which i assume plasmashell is using). I'm not familiar with plasmashell or startkde but maybe it has some option to fix it too.

**Comment by haadr** [comment]
You can tell plasmashell to run applications via a terminal, but then the terminal is opened in addition to the application and stays around as a separate window. Now that I know this is how they get loaded however, one can just write a launcher script to load the desired environment before launching nvim-qt as well. 

However, if the Mac OS X workaround is portable, it probably makes sense to turn it into a flag, since most people who use graphical front ends to nvim/vim are likely to launch them via a window manager.

**Comment by equalsraf** [comment]
> However, if the Mac OS X workaround is portable, it probably makes sense to turn it into a flag, since most people who use graphical front ends to nvim/vim are likely to launch them via a window manager.

This is actually not that common. It depends on how your desktop environment is started too. In linux at least the stuff from .profile should be loaded.

The mac os code should be portable for shells where the `$SHELL -l -c env -i` works. AFAIK most linuxes and at least openbsd.

**Comment by haadr** [comment]
Interesting! It seems like I do get lots of "standard" environment variables, but nothing from my bashrc. $SHELL is available though from inside nvim-qt for me when started via plasmashell though and that command works for me.

**Comment by ag-eitilt** [comment]
Sorry to revive something so old, but is there a known workaround for Mac-style initialization on XFCE (via MX Linux)?  The code (now [a few lines lower](https://github.com/equalsraf/neovim-qt/blob/b4ca557cd133eb049cf4c977a81437a23a1fcd06/src/gui/app.cpp#L179)) looks like it's still fenced behind an OS define rather than a runtime flag, but I'm not getting my full set of environment variables -- the mentioned `:!$SHELL -l -c env -i` shows them and they correctly appear in `:terminal`, but neither `:!env`, vimscript, nor Lua `vim.env` provides them, even if I mark 'Run in terminal' in the launcher.  I've seen a suggestion elsewhere to put environment variables in the nvim-qt.desktop file itself, but in order to keep everything across my entire system updated I've put the setup in a file, and (while it's not your problem) `Exec=source ~/.profile.env ; nvim-qt -- %F` for some reason prevents NVimQT from starting at all.  I am definitely sourcing that environment file from my `.bashrc` and while I don't know how to test it, *should* be doing the same from my `.profile`.

**Comment by ag-eitilt** [comment]
Figured that was it, but wanted to ask here just in case -- I've not seen anything solving it on the WM/dock end *yet*, so if you did have some magic option it would have been an easy toggle before diving deeper.  Thanks for the response!
