### ISSUE TITLE
GVIMINIT environment variable

### ISSUE THREAD

**Issue by legendre6891** [equalsraf/neovim-qt#452]
The help page `:help gui-init` reads
```  
... snipped ...

- If the GVIMINIT environment variable exists and is not empty, it is
    executed as an Ex command.

... snipped ...
```

However, it seems this is not supported? I tried with

```
GVIMINIT='echom 'HELLO"' nvim-qt
```

and no messages are placed in the messages buffer. It works with vanilla `gvim` (i.e. vim's gvim, compiled with GTK2). 

Is this intentional?

**Comment by equalsraf** [comment]
> Is this intentional?

No. I was not aware of this feature.

It seems GVIMINIT was supported in vim but it is currently not supported in neovim. This is not surprising since the GUI is no longer part of neovim core. I don't know if any of the other neovim GUIs support this feature.

It seems like this would not be too hard to implement. However I am not quite sure what is the expected behaviour. I assume the contents of $GVIMINIT are executed before the contents of ginit.vim, but after init.vim. I would have to check the Vim source code to confirm this. A grep of the neovim source code shows that this variable is only mentioned in the documentation.

It is important to remember here that the meaning of these options is not identical in vim and neovim. Because a neovim GUI attach and detach from the neovim process, which means $GVIMINIT could be executed at each attachment.

I see a couple of ways to implement this

1. either [here](https://github.com/equalsraf/neovim-qt/blob/master/src/gui/shell.cpp#L145) with a call to `nvim_command(getenv("GVIMINIT"))`
2. or in the GUI [shim](https://github.com/equalsraf/neovim-qt/blob/master/src/gui/runtime/plugin/nvim_gui_shim.vim#L6) keeping in mind the command will only be executed when the first GUI attaches

**Comment by legendre6891** [comment]
Thank you, @equalsraf, for the explanation. I'll leave it to your judgment on which method fits best; my original use case for this was to figure out a way to certain GUI-related configuration to only be executed for `nvim-qt` and not other GUIs (e.g. oni). The idea was to create a wrapper shell script:

```
GVIMINIT='source("nvim-qt-gui.init")' nvim-qt
```

By the way, it is _not_ the case that the contents of GVIMINIT are executed before the contents of `ginit.vim`, insofar as the manual indicates. It reads
```
. . . snip . . .

- The following are tried, and only the first one that exists is used:
  - If the GVIMINIT environment variable exists and is not empty, it is
    executed as an Ex command.
  - If the user gvimrc file exists, it is sourced.  The name of this file is
    normally "$XDG_CONFIG_HOME/nvim/ginit.vim" ($XDG_CONFIG_HOME defaults to 
    ~/.config).

. . . snip . . .
```

**Comment by equalsraf** [comment]
> By the way, it is not the case that the contents of GVIMINIT are executed before the contents of ginit.vim

Oh, good catch. That limits my options, we need to do it in C++ (option 1).

> my use case for this was to figure out a way to certain GUI-related configuration to only be executed for nvim-qt and not other GUIs (e.g. oni).

As for this use case there are other options.

If you are creating a wrapper anyway then you can pass commands to nvim e.g. `nvim-qt -- --cmd "let g:NvimQt=1"`. The variable is them available in ginit.vim.

```vim
if exists('g:NvimQt')
	echom "Oh no ..."
endif
```

In any case, I'm ok with adding a similar global variable to support this use case.

**Comment by legendre6891** [comment]
> If you are creating a wrapper anyway then you can pass commands to nvim e.g. nvim-qt -- --cmd "let g:NvimQt=1". The variable is them available in ginit.vim.
> 
> if exists('g:NvimQt')
> 	echom "Oh no ..."
> endif

Ah that's right -- I hadn't thought of this!

> In any case, I'm ok with adding a similar global variable to support this use case.

That would be very welcome. Shall I create another issue to track this?

**Comment by equalsraf** [comment]
> That would be very welcome. Shall I create another issue to track this?

Please do, it should be a one line patch but good suggestions for variable names are welcome.

For GVIMINIT I've started #453.
