### ISSUE TITLE
How to disable autocomplete GUI?

### ISSUE THREAD

**Issue by RevoNova** [equalsraf/neovim-qt#506]
What shows up on nvim-qt:
![unwanted](https://user-images.githubusercontent.com/35003073/51228880-d586ae00-198c-11e9-8b18-75fb7a162775.PNG)

What I want (from nvim):
![wanted](https://user-images.githubusercontent.com/35003073/51228901-ee8f5f00-198c-11e9-9ea5-64b45b26406a.PNG)

**Comment by gagbo** [comment]
Add `GuiPopupMenu 0` in your `ginit.vim` (Or use :GuiPopupMenu 0 in a running session).

**Comment by gagbo** [comment]
Related to #496, which may be a solution to dynamically theme these child widgets

**Comment by RevoNova** [comment]
Thanks,
`:GuiPopupmenu 0` works

**Comment by prabirshrestha** [comment]
I do find this very irritating behavior that I need to use `ginit.vim` instead of just `init.vim`.

Tabs are worse than popup. Dosn't look polished at all. This one doesn't bother me much because I don't use tabs except when using gina.vim 

![image](https://user-images.githubusercontent.com/287744/51276628-14673480-198a-11e9-92b8-cdf5e686fb0e.png)

Can this be defaulted to 0? Or is it 1 because it is a test bed for nvim to try out external gui.

**Comment by justinmk** [comment]
> I do find this very irritating behavior that I need to use ginit.vim instead of just init.vim.

Yes, and `:help dev-ui` encourages UIs to avoid such mechanisms:

```
- Call |nvim_set_client_info()| after connecting, so users and plugins can
  detect the UI by handling the |ChanInfo| event. This avoids the need for
  special variables and UI-specific config files (gvimrc, macvimrc, …).
```

Since Nvim 0.3.1, the recommended mechanism is `ChanInfo` to allow user config/plugins to react to UI capabilities.

> Can this be defaulted to 0? Or is it 1 because it is a test bed for nvim to try out external gui.

Neither. What's unpolished about GUI tabs that adopt the OS theme?

**Comment by equalsraf** [comment]
> I do find this very irritating behavior that I need to use ginit.vim instead of just init.vim.

I was going to say maybe you can ... and then I realised there is an open PR from me that has been sitting there for 1.5 years https://github.com/neovim/neovim/pull/6917 ... yeah :man_facepalming:

So while I cover in deep shame, some followups:

1. Whats wrong with the tabs, that seems like the default Qt theme in your system. Is it because they have no buttons, or is it the `[]`?
2. is nvim using `guioptions` for anything? That used to be the place for this kind of stuff in vim.

> Can this be defaulted to 0? Or is it 1 because it is a test bed for nvim to try out external gui.

My discretion is usually the only thing that defines 0 or 1. Tabs are a stable thing in neovim and there were no downsides to turning them on.  We could probably add a close button on them though.

**Comment by Kraust** [comment]
FYI it seems to be `GuiPopupmenu 0` and not `GuiPopupMenu 0` if anyone's confused.

**Comment by Awpteamoose** [comment]
Neither `:h nvim-gui-shim` nor `GuiPopupmenu 0` work, the correct one is `call rpcnotify(0, "Gui", "Option", "Popupmenu", 0)`

**Comment by equalsraf** [comment]
hi @Awpteamoose 

> Neither :h nvim-gui-shim nor GuiPopupmenu 0 work, the correct one is call rpcnotify(0, "Gui", "Option", "Popupmenu", 0)

If both of those do not work, then it seems the gui plugin is not being loaded. How did you install nvim-qt? and what system are you running?

**Comment by Awpteamoose** [comment]
> How did you install nvim-qt? and what system are you running?

Windows 10, downloaded 0.3.4 from [here](https://github.com/neovim/neovim/releases).

**Comment by equalsraf** [comment]
mmm, dont have windows to reproduce, but

- calling `:scriptnames` should show a nvim_gui_shim.viim being loaded.
- `echo &rtp` should include the location of the gui plugin

**Comment by Awpteamoose** [comment]
`:scriptnames` shows `neovim\share\nvim-qt\runtime\plugin\nvim_gui_shim.vim`
`echo &rtp` shows a bunch of neovim plugin paths and `neovim\share\nvim-qt\runtime`

**Comment by equalsraf** [comment]
well i'm stumped :S

**Comment by A5H1Q** [comment]
> Neither `:h nvim-gui-shim` nor `GuiPopupmenu 0` work, the correct one is `call rpcnotify(0, "Gui", "Option", "Popupmenu", 0)`

You saved my day

**Comment by JohnDowson** [comment]
Neither GuiPopupMenue nor GuiTabline work when put into a ginit.vim, but they do work when executed with `:`. I'm on Windows 10 as well.
