### ISSUE TITLE
Warning after every keypress

### ISSUE THREAD

**Issue by ptersilie** [equalsraf/neovim-qt#507]
When running neovim-qt from the terminal, I'm getting the following warning every time I press a key:
```
Received unknown redraw notification "flush" ()
```

I'm also getting the following startup warnings (not sure if they are related):
```
Received unknown option "ext_linegrid" QVariant(bool, false)
Received unknown option "ext_hlstate" QVariant(bool, false)
```

**Comment by gagbo** [comment]
It's not really related. It's safe to ignore these messages. You're getting these messages because `qDebug()` messages are not filtered out in your configuration. I'm not sure about the best way to handle this.

If you do not care at all, I installed `kdebugsettings` which is a GUI to allow you to add rules about when to print or not to print debug messages (depending on their category).

What's your OS by the way ? On Fedora I had these messages turned off by default

**Comment by ptersilie** [comment]
I'm running Arch. Can I turn them off in `ginit.conf` or does `neovim-qt` have its own config file where I can do that?

**Comment by equalsraf** [comment]
The messages are harmless debug messages.

Those usually should not show up in a release build. Did you build from source or are you using a package from somewhere else.

**Comment by ptersilie** [comment]
I know they are harmless but they are pretty annoying as they appear on every keypress. I'm using the version from the Arch User Repo (https://aur.archlinux.org/packages/neovim-qt-git/), so you might be right, that this isn't a release build. I'll try building it myself and see if that fixes the problem. Thanks for the help!

**Comment by ptersilie** [comment]
Turns out I wasn't installing from the AUR, but from the official Arch repositories, which has the latest release (0.2.12). If I build from source (tag 0.2.12) the warnings disappear. So it seems to be a problem with the package in the official repo.
