### ISSUE TITLE
ginit, fileencoding, unable to close unmodified file with :q

### ISSUE THREAD

**Issue by fekir** [equalsraf/neovim-qt#545]
Hello,

I have following problem with version 0.3.4 to version 0.3.7 on GNU/Linux and Windows.

Given a ginit.vim file, with only

`````
:set fileencoding=utf-8
`````

then, after opening a binary file with nvim-qt, not editing/changing it in any way, and then trying to close it, I get following error message:

    E37: No write since last change (add ! to override) 

I I try to undo with `u`, I get

    Already at oldest change

as message.

Notice that nvim, with a init.vim file with only

`````
:set fileencoding=utf-8
`````

does not show the same behavior, I can open and close binary files without any errors.

**Comment by equalsraf** [comment]
Does this also happen with regular nvim? I can observe the exact same behaviour with nvim in the terminal, by simply calling `:set fileencoding=utf-8` on an empty file.

For the confusing situation with undo/fileencoding you can open an issue in neovim/neovim, but notice the docs already describe this behaviour (from :h fileencoding)

> When this option is set, after starting to edit a file, the 'modified'
> option is set, because the file would be different when written.

The only workaround I could find was to unset fileencoding and then quit.

I'm not entirely sure what you were trying to do by setting fileencoding in the config file, since this option is local to the buffer it does not make a lot of sense to set it there. Usually the option you want is fileencodings (plural) which should already include utf8 anyway. **fileencoding** is also set on autocommands for different flle types but setting it globally does not seem to have the intended effect..

**Comment by fekir** [comment]
>Does this also happen with regular nvim?

No, if the setting written only in `init.vim`, both nvim and nvim-qt do not have any issues closing a binary file.
The issue only arises with `nvim-qt`, and the settings written to `ginit.vim`

> I can observe the exact same behaviour with nvim in the terminal, by simply calling `:set fileencoding=utf-8` on an empty file.

Mhm.
If the file exists, I cannot reproduce this behaviour, it only happens if the file does not exists (both with `nvim` and `nvim-qt` and both windows and GNU/Linux)

> I'm not entirely sure what you were trying to do by setting fileencoding [...]

I can somehow remember that placed in the config file, it should it state that the encoding of the configuration file is utf-8, but can't find a reference in the help page.
But the help page also states:
> For a new file the global value of 'fileencoding' is used.

So settings `fileencoding` in the config would make sense when creating new files, no?

> Usually the option you want is fileencodings [...]

Mhm, maybe you are right and I actually wanted  `fileencodings` in my config (wouldn't actually hurt) without noticing the typo, can't really remember...
