### ISSUE TITLE
show the drag handle when mouse cursor is in the split window zone

### ISSUE THREAD

**Issue by prabirshrestha** [equalsraf/neovim-qt#57]
need `<-->` cursor in near the window split zone. Although mouse split does work already.

**Comment by equalsraf** [comment]
I think this requires some changes upstream, not seeing an API event for this.

**Comment by christianrondeau** [comment]
I wanted to log something because "dragging splits was not implemented", but after reading this issue, I realized this was simply me not having actually tried!

I think this does warrants an upstream issue (I don't feel knowledgeable enough to ask the "right thing" upstream, if someone wants to help and create the issue).

My understanding is that neovim-qt would either require knowledge of where splits are (would potentially allow fancier rendering of splits), or receive some specific indications of which "cursor" is to be expected for each "character" (would allow fancier window-like UI within vim, e.g. the confirm popup), if that helps.
