### ISSUE TITLE
Unknown font: on latest nvim release

### ISSUE THREAD

**Issue by cmaughan** [equalsraf/neovim-qt#585]
I updated to Neovim 4.2, released yesterday.  When running nvim-qt I now get a startup error:
```
Unknown font:
```
I'm on windows.  I've tried it with NORC.  Same behavior.  nvim is fine, but nvim-qt is not.

**Comment by jgehrig** [comment]
Thanks @cmaughan!

I would guess this is related to #575 and #583 . I can investigate on a Windows machine later today.

If you can compile and test, try deleting the following lines from `shellwidget.cpp`:
```C++
// Issue #575: Clear style name. The KDE/Plasma theme plugin may set this
// but we want to match the family name with the bold/italic attributes.
f.setStyleName("");
```

**Comment by jgehrig** [comment]
I can't reproduce the issue (Windows or Linux).

Can you provide any additional details? How did you install?

Can you remove the line above, compile, and test?

**Comment by cmaughan** [comment]
I'm not setup to compile this project, but I can try; I installed by just taking the latest neovim release and extracting it.
Somebody told me yesterday that on the reddit release thread there was a comment that the windows version needed more 'finessing'!  I don't have the link though.

**Comment by cmaughan** [comment]
Note, I'm on Windows 
Version	10.0.17763 Build 17763

**Comment by blueyed** [comment]
Another report: https://github.com/neovim/neovim/issues/11037

**Comment by jgehrig** [comment]
I still cannot reproduce the issue on Windows 10, 10.0.18362 Build 18362 x64.

An explicit set of steps would be helpful: specific links, install location, every step/action, etc. 

@cmaughan 
 > I installed by just taking the latest neovim release and extracting it.

This is good to know, I installed from a different source. Do you have any more details?

@the42
Any additional details you can provide would be helpful.

**Comment by cmaughan** [comment]
Steps:
1. Go to: https://github.com/neovim/neovim/releases
2. Download the 0.4.2 release (nvim-win64.zip)
3. Using WinZip, extract to a folder on your drive (for me this is c:/tools/neovim).
4. Open a windows command prompt.  
5. Navigate to c:/tools/neovim (if not in your path)
6. Run nvim-qt.exe

**Comment by somini** [comment]
I can reproduce this on Linux (ArchLinux; nvim v0.4.2, nvim-qt v0.2.14-1).

**Comment by somini** [comment]
> I can reproduce this on Linux (ArchLinux; nvim v0.4.2, nvim-qt v0.2.14-1).

Downgrading neovim-qt to v0.2.13-1 (previously installed version) does not solve the issue.

**Comment by cmaughan** [comment]
Perhaps the bug is dependent on which fonts you have installed on your system?  Just a thought....

**Comment by somini** [comment]
> Perhaps the bug is dependent on which fonts you have installed on your system? Just a thought....

This is possible, but that mean neovim-qt is hardcoding a default font?

**Comment by jgehrig** [comment]
> This is possible, but that mean neovim-qt is hardcoding a default font?

This was my next thought. I didn't suspect this because the default value (hardcoded) hasn't changed with the latest release.

> Downgrading neovim-qt to v0.2.13-1 (previously installed version) does not solve the issue.
Interesting! This would suggest a hardcoded font issue...

On Windows, it is Consolas:
https://github.com/equalsraf/neovim-qt/blob/b25f0c615df9e6f0a886eb9b2ecd2a5bd30fbbd3/src/gui/shellwidget/shellwidget.cpp#L33

On Linux, it is "Monospace":
https://github.com/equalsraf/neovim-qt/blob/b25f0c615df9e6f0a886eb9b2ecd2a5bd30fbbd3/src/gui/shellwidget/shellwidget.cpp#L35

**Comment by the42** [comment]
:GuiFont says it's using Consolas and Consolas is installed

**Comment by oczekp** [comment]
hi Guys,

if it will help I have the same issue on my Windows 10. I compiled the code with suggested by @jgehrig  fix:
Now it is:

`// Issue #575: Clear style name. The KDE/Plasma theme plugin may set this
// but we want to match the family name with the bold/italic attributes.
// f.setStyleName("");`

but the problem still remains, and on startup got:
`Unknown font:`

When running :GuiFont it says `Consolas:h9`.
Tested also running nvim-qt -- -u NONE and error still appears.
I have also changed font to Courier inside the ginit.vim and got same result. Hope it will help somehow.

**Comment by cmaughan** [comment]
I came across this in nvim_gui_shim.vim.  I don't know much vim script, or how nvim-qt works, but it strikes me as interesting that this seems to force an empty looking thing across the wire to the server.
And if fname were also empty, you'd get similar behavior....

```
" Set GUI font
function! GuiFont(fname, ...) abort
  let force = get(a:000, 0, 0)
  call rpcnotify(0, 'Gui', 'Font', a:fname, force)
endfunction
```

**Comment by oczekp** [comment]
I am not sure if this is the problem, as I removed nvim_gui_shim.vim at all, remove ginit.vim and run nvim-qt -- -u NONE and event there is no call of GuiFont problem still occurs.
I've added some additional checks and I see that on startup nvim-qt calls handleRedraw function with name set to "option_set" for
`name=arabicshape, and value=true`
`name=ambiwidth, and value=single`
`name=emoji, and value=true`

and finally:
`name=guifont, and value='' //empty`

later
`name=guifontset, and value='' //empty`
`name=guifontwide, and value='' //empty`
`name=linespace, and value=0`
...

and problem is for guifont, as it propagate later empty string which causes error.

**Comment by jgehrig** [comment]
@oczekp Thanks! Your build suggests this bug is not caused by the changes for Issue 575....

@cmaughan The function you pointed out looks reasonable... The vimscript adds an optional parameter `force`. It calls the function `bool setGuiFont(const QString& fdesc, bool force = false);` The option allows users to display non-monospace fonts, despite any warnings.

Removing `nvim_gui_shim.vim` is not the correct solution, without that file you will not be able to interact with various gui features.

The error probably comes from this snippet:
https://github.com/equalsraf/neovim-qt/blob/b25f0c615df9e6f0a886eb9b2ecd2a5bd30fbbd3/src/gui/shellwidget/shellwidget.cpp#L52-L57

Is there an error when either of the following commands are run?
`:set guifont=Consolas:h11`
`:GuiFont Consolas:h11`

What I don't understand... What causes only some machines to trigger these errors? Why?

**Comment by the42** [comment]
> :set guifont=Consolas:h11
> :GuiFont Consolas:h11

I am not 100% certain as I do momentarily not gave access to the Windows machine having the error but I have dractional scaling set to 125% and I am very certain rhat my :GuiFont was Consolas:h11 from the start, causing an error

**Comment by oczekp** [comment]
thanks @jgehrig for your feedback.
In my case this error appears always on startup, but sometimes is not visible and I have to run:
`:messages` to see it.

Flow seems to be:
`void Shell::handleNeovimNotification(const QByteArray &name, const QVariantList& args)
inside that function:
`const QVariantList& opargs = opargs_var.toList();`
`handleRedraw(name, opargs);`
which calls later:
`handleSetOption(opargs.at(0).toString(), opargs.at(1));`
opargs.at(0).toString() seems to be fine set to 'guifont'
but opargs.at(1) is empty.

When adding for example set guifont=Courier:h9 in the init.vim I see that it appears as well later with proper data:
opargs.at(0).toString() seems to be fine set to 'guifont'
and opargs.at(1) is Courier:h9.

In the logs I have then:
redraw with 'guifont' and empty opargs.at(1) <- coming from don't know where:) which causes error with guifont to be displayed
then later
readraw with 'guifont' and Courier:h9 <- coming from init.vim

This seems to be very initial redraw request with guifont coming from nvim. I am not very familiar maybe it is  designed this way that nvim sends guifont request on init with empty arguments, or maybe a bug in nvim.

**Comment by jgehrig** [comment]
@oczekp This is exactly the type of information I was hoping to find. Thanks!

I think you may be onto something with nvim sending `set guifont={empty}` on startup...

What is the output of `nvim --version`? (I assume v0.4.2)
What happens when you run with an older version?

For example, I can run an arbitrary development version with:
`VIM_RUNTIME=~/Development/neovim/runtime NVIM_QT_RUNTIME_PATH=~/Development/neovim-qt/src/gui/runtime ./nvim-qt --nvim ~/Development/neovim/build/bin/nvim`

**Comment by oczekp** [comment]
@jgehrig I think you are right.
I've checked the code of nvim and see that they got file called options.lua and there is:

>   {
      full_name='guifont', abbreviation='gfn',
      type='string', list='onecomma', scope={'global'},
      deny_duplicates=true,
      vi_def=true,
      varname='p_guifont',
      redraw={'ui_option'},
      defaults={if_true={vi=""}}
    },

I guess this is used as init data that nvim sends by default on startup to nvim-qt. Please check defaults section which is empty:)

I've checked the rest of the parameters and they also looks exactly as the ones from that file, for example `ambiwidth`:
>   {
      full_name='ambiwidth', abbreviation='ambw',
      type='string', scope={'global'},
      vi_def=true,
      redraw={'all_windows', 'ui_option'},
      varname='p_ambw',
      defaults={if_true={vi="single"}}
    },

**Comment by somini** [comment]
It seems this is moving forward, but I'll add my Linux information.

> Is there an error when either of the following commands are run?
> `:set guifont=Consolas:h11`
> `:GuiFont Consolas:h11`

On my Arch Linux machine:

```
GuiFont Monospaced
  Monospaced is not a fixed pitch font
```

Running `GuiFont` shows me the correct value `Liberation Mono:h11`.

When I say "correct", I mean what fontconfig provides:
```
$ fc-match Monospace
LiberationMono-Regular.ttf: "Liberation Mono" "Regular"
```

**Comment by jgehrig** [comment]
@oczekp I can reproduce this issue now. Thanks!

I am confident the error is caused by a behavior change in neovim.

A fix should be easy. We can modify `bool setGuiFont(...)` so that it does not emit an error message for this case. The description for `:help guifont` is a little vague, I think we can safely ignore `fdesc == ""`.

**Comment by jgehrig** [comment]
@somini That info is helpful info. Thanks!

Your commands support our suspicions... Also, it looks like our default font selection on Linux could use some work.

**Comment by somini** [comment]
> Your commands support our suspicions... Also, it looks like our default font selection on Linux could use some work.

IMHO `monospace` is good enough, it should select the most appropriate font. I'm on i3 with a barebones installation, I don't have many fonts installed. I think on KDE and GNOME it should pickup the "native" font for the system, configurable somewhere.

**Comment by cmaughan** [comment]
I built and installed nvim-qt this morning with the patch - it works for me :)
