### ISSUE TITLE
Other font weight for GuiFont

### ISSUE THREAD

**Issue by hosxy** [equalsraf/neovim-qt#597]
Could you please add other font weight (eg: semibold,) or add an arguments to provide font weight  for GuiFont  ?

**Comment by equalsraf** [comment]
Is there any expected unit of weight for this?

Qt uses a scale of 0-99 for font weights, where 50 is Normal and 75 is Bold. The only intermediate value listed is 63 (called DemiBold). Anyway these seem consistent with vim-gtk:

- https://doc.qt.io/qt-5/qfont.html#Weight-enum
- https://vim.fandom.com/wiki/Setting_the_font_in_the_GUI

Not sure how this will play out with font metrics, but otherwise I dont see a reason not to do it.

It sounds like the implementation would be similar to the font height **hXX** (except this one is an integer). I do not want to use **wXX** here as it clashes with the width (which we dont support but vim in Mac OS does).

https://github.com/equalsraf/neovim-qt/blob/9875617f1f471031ee48cb4f51757ba73e08833b/src/gui/shell.cpp#L111-L118

**Comment by jgehrig** [comment]
Closing. Since Pull #651, arbitrary font weight can now be set:

See `:help GuiFont`:
```
The following attributes are available

	hXX - height is XX in points (can be floating-point)
	wXX - weight is XX
	b   - bold weight
	sb  - semibold weight
	l   - light weight
	i   - italic
```

Under the hood, we're using [QFont::Weight](https://doc.qt.io/qt-5/qfont.html#Weight-enum). The range set of valid ranges [0-99].

NOTE: Rendering is handled by Qt, and you may not get full granularity on all platforms. Similar to #650.
