### ISSUE TITLE
Mouse scrolling with anchor

### ISSUE THREAD

**Issue by eyalk5** [equalsraf/neovim-qt#611]
Hi,
It would be really nice if the style of mouse scrolling in windows(I think) would be somehow supported in neovim-qt.
That is, when you press the middle mouse button, you get an anchor, and depending on the position relative to it, the scroll speed is set.

Thanks.

**Comment by Nuclearo** [comment]
That sounds interesting. I don't think it would feel as smooth, given how scrolling in vim is done in whole lines rather than pixels, but I can imagine it would scroll a line every `x` seconds, with `x` being determined by your cursor position away from the anchor.
One thing to consider is that currently middle clicking does paste, at least on Linux. Changing that just on windows would maybe make it fit in better, but be a bit inconsistent across platforms.

**Comment by eyalk5** [comment]
I am using macos. I don't think the defaults are that important. It could be a feature that can be turned on.

**Comment by equalsraf** [comment]
I'm not very familiar with mac OS internals but I would assume this is implemented by the system rather than by individual apps, but I could be wrong.

The first reference I found was the [SO question](https://superuser.com/questions/303424/can-i-enable-scrolling-with-middle-button-drag-in-os-x) that mentions some apps to support this on Mac.

The Qt docs mention QSCrollEvent for kinetic scrolling, but I'm not sure that works. There is a QScroller class to setup mouse gestures.

**Comment by jgehrig** [comment]
This would conflict with the default Vim behavior. Vim follows Linux's pattern of copy-on-select and paste-on-middle-click. I think the many users expect this.

Any solution here must not conflict with the existing behavior and must be opt-in. Open to Pull Requests.

Since I don't have the time to implement this, closing.
