### ISSUE TITLE
Cannot connect to Neovim <= v0.2.0

### ISSUE THREAD

**Issue by jgehrig** [equalsraf/neovim-qt#625]
Attempting to run `nvim-qt` with old versions of `nvim` does not work.

The connector eventually times out with error message:
```
$ VIM_RUNTIME={nvim-runtime} NVIM_QT_RUNTIME_PATH={nvim-qt-runtime} nvim-qt --nvim /path/to/nvim-0.3.1/build/bin/nvim
Neovim API version compatible with 0 supported 4
Request 3 timed out: 34
Neovim fatal error "Neovim is taking too long to respond"
```

This issue was discovered while testing Pull Request #623.

If this issue is fixed, it may be worth testing the behavior for `hl_id` vs `attr_id` mentioned in guicursor.

**Comment by equalsraf** [comment]
I just rebuilt v0.3.0 here and was able to connect via socket.

I did get a similar issue when starting using `--nvim` however this was happening because nvim was blocking on an error (because it could not find some runtime files) - this caused the GUI to timeout.

```
VIMRUNTIME=../runtime/ nvim-qt --nvim bin/nvim
```

or alternative with `-u NONE` also works

```
nvim-qt --nvim bin/nvim -- -u NONE
```

**Comment by equalsraf** [comment]
The minimum required neovim version should be API version 1 (nvim 0.1.6) and I am able to launch it with nvim-qt. I do get some errors because them GUI shim tries to setup notifications for DirChanged.

Launching with nvim 0.1.5 will cause nvim-qt to complain with 

```
Neovim API version compatible with 0 supported 0
This instance of neovim DOES NOT support api level 1
QObject::connect: invalid null parameter
This instance of neovim DOES NOT support api level 1
```

I did run into some difficulties while rebuild the 0.1.* versions with some third-part dependencies not building but it seems they were available in my system anyway.

**Comment by jgehrig** [comment]
It looks like I had a typo above, `VIM_RUNTIME` should be `VIMRUNTIME`. Whoops!

With the typo fixed, I can get versions down to 0.2.0 running. I'm not sure why 0.1.6 or 0.1.7 don't work?

I also see the issues with `treeview.cpp`, it looks like the following statement can evaluate to `nullptr`:
`m_nvim->neovimObject()`

**Comment by equalsraf** [comment]
Strange what exactly happens when you try to run?

Perhaps trying to attach to a running instance makes it easier to debug.

```
$ NVIM_LISTEN_ADDRESS=/tmp/nvim-016  bin/nvim -u NONE
```

and then call nvim-qt using --server. My debug build off the tip of master gets me the following messages but otherwise works.

```
$ nvim-qt --server /tmp/nvim-016 
Neovim API version compatible with 0 supported 1
This instance of neovim not support api level 2
This instance of neovim not support api level 4
```

(on a side note I very much like the new --version)

```
$ nvim-qt --nvim build/bin/nvim --version
NVIM-QT v0.2.14.0
Build type: 
Compilation: -Wall -Wextra -Wno-unused-parameter -std=c++11 -Wfatal-errors
Qt Version: 5.11.1
Environment: 
  nvim: build/bin/nvim
  args: --cmd let &rtp.=',/home/raf/.local/share/nvim-qt/runtime' --cmd set termguicolors
  runtime: /home/raf/.local/share/nvim-qt/runtime

NVIM v0.1.6
Build type: Dev
Compilation: /usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/raf/Code/neovim/build/config -I/home/raf/Code/neovim/src -I/usr/include -I/home/raf/Code/neovim/.deps/usr/include -I/home/raf/Code/neovim/.deps/usr/include -I/home/raf/Code/neovim/.deps/usr/include -I/usr/include -I/usr/include -I/usr/include -I/home/raf/Code/neovim/build/src/nvim/auto -I/home/raf/Code/neovim/build/include
Compiled by raf@kai

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```

**Comment by jgehrig** [comment]
Part of the issue is a nullptr dereference from teeview above.

I plan on debugging this fully at some point. I'd guess there aren't many people running this configuration.

> (on a side note I very much like the new --version)
Yes! I was very excited to see this in 641 :)

It was much easier to debug.
