### ISSUE TITLE
Nvim-qt ignores theme within popup

### ISSUE THREAD

**Issue by YVEF** [equalsraf/neovim-qt#717]
Operating System: Linux
Nvim-qt version: 0.2.16.1
Theme: 'miramare' (but I checked with other themes)

Hi everyone. I use Omnisharp + Coc.nvim for autocomple. And when the Nvim opens through terminal it work fine, but if I use the qt client, the popup ignores my theme. I have attached screenshots.
I'm not sure if this is bug, but I just want to know how I can fix it.

From terminal:
![Screenshot from 2020-06-28 17-37-56](https://user-images.githubusercontent.com/44643054/85954530-a50bb780-b967-11ea-81f2-d4f940128929.png)

From qt client:
![Screenshot from 2020-06-28 17-45-41](https://user-images.githubusercontent.com/44643054/85954545-bbb20e80-b967-11ea-81a8-65406710f3ce.png)

Thank you.

**Comment by jgehrig** [comment]
@YVEF 

You need to set `:GuiPopupmenu 0` in `ginit.vim`. See `:help nvim-gui-shim` for more details.

The color scheme is pulled from Qt, and not Neovim. This issue is on my radar, I have some upcoming changes around using the Neovim fonts and color to stylize Qt UI elements in `neovim-qt`. Stay tuned...

**Comment by YVEF** [comment]
@jgehrig Thank you a lot.
I will close the issue.
