### ISSUE TITLE
Ligatures not worked?

### ISSUE THREAD

**Issue by RealXIHNIK** [equalsraf/neovim-qt#723]
Ligatures don't work

My Font: Fira Code
Program: neovim-qt
Linux Mint

---

Path:
~/.config/nvim/ginit.vim

Contains:
GuiFont FiraCode NF:h12

[Fira Code Regular Nerd Font Complete Mono Windows Compatible.otf.zip](https://github.com/equalsraf/neovim-qt/files/4921956/Fira.Code.Regular.Nerd.Font.Complete.Mono.Windows.Compatible.otf.zip)

Quetion: What i need do to make ligatures work in neovim-qt?

**Comment by jgehrig** [comment]
This is a known issue, see Pull Request #470

It is on my radar, hopefully we can figure this out by the next release.

**Comment by jgehrig** [comment]
@RealXIHNIK Ligatures do not currently work.

That Pull Request is the code required to make Ligatures work with neovim-qt. You'd need to build that code....

However, there are some outstanding concerns with font spacing and the code is not currently mergable due to conflicts. Generally it works, but is not officially supported.

**Comment by jgehrig** [comment]
Ligatures are now available in `master`, run `:GuiRenderLigatures 1`.

The feature should be available for release `0.2.17`.
