### ISSUE TITLE
Double quote character entered on Ctrl+Win; makes it hard to switch between virtual desktops

### ISSUE THREAD

**Issue by balazsbotond** [equalsraf/neovim-qt#796]
- **Operating system:** Windows 10 Pro 19042.630
- **Binary build:** The one distributed with neovim 0.4.4, installed with scoop (I couldn't determine the neovim-qt version because it doesn't have a `--version` switch and the `--help` doesn't list any alternative option).

**Steps to reproduce:**

1. Create at least one additional virtual desktop (Win+Tab, then click "New Desktop").
2. Open neovim-qt and wait until it loads
3. Switch away from the current desktop using the Ctrl+Win+Right/Left Arrow shortcut
4. Switch back to the previous desktop (doesn't matter if using a shortcut or the Windows GUI)
5. A `"` character appears in neovim-qt (in normal mode, at the bottom right of the window, in insert mode it is inserted)

**Screenshot:**

![image](https://user-images.githubusercontent.com/2791280/100545486-4f13a680-325c-11eb-8ed8-d9f4bba0d3fe.png)

**Details:**

First of all, I'd like to thank you for developing neovim-qt. I use it as my main code editor on Windows and it is extremely useful.

I've found something which may be a bug. I use a lot of virtual desktops and switch between them using the Ctrl+Win+Left/Right arrow shortcut. I've found that whenever I press Ctrl+Win, it inputs the `"` (double quote) character in neovim-qt (it doesn't matter whether I'm in normal or insert mode). When I switch back to the desktop with neovim-qt, the `"` is waiting there silently, ready to ruin whatever command I'm about to enter first. I can work around it by always pressing Esc first, but it's, to be honest, very uncomfortable and easy to forget.

**Comment by jgehrig** [comment]
Thanks for the kind words! :smile:

For me, this issue is resolved with the latest Windows build from master: https://ci.appveyor.com/api/buildjobs/u85hm5wn4wex3wfr/artifacts/neovim-qt.zip

You're running a relatively old version of neovim/neovim-qt. There hasn't been an official release of neovim for some time since they're working on a major 0.5.x release. I would recommend updating one or both packages.

I recommend using neovim 0.5.0 (nightly or pre-release) with a recent neovim-qt release (0.2.16.1 or master). Current neovim nightly builds include neovim-qt 0.2.16.1.

I'm not very familiar with scoop, but you can try this scoop nightly:
https://github.com/wsdjeg/scoop-neovim-dev

There have been a handful of input layer improvements since that release. Let me know if you still see any issues with the build above.

**Comment by balazsbotond** [comment]
Thank you for the quick reply! I've just installed the nightly from the scoop bucket you recommended and it works flawlessly.
