### ISSUE TITLE
Support stylistic sets for ligature fonts

### ISSUE THREAD

**Issue by Melkster** [equalsraf/neovim-qt#811]
So there's an issue to [add ligature support](https://github.com/equalsraf/neovim-qt/issues/166), which seems to have been resolved in master.

But is there any planned support for [stylistic sets for ligatures (here described for the font FiraCode)](https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets) as well?

**Comment by jgehrig** [comment]
No, there's no active plan. I wasn't aware of this option for Fira Code. Now I know...

Basic ligature features still need work. I need to finish that work first before I have time for features such as stylistic sets.

If you'd like to work on this feature, I'm open to it and happy to review/merge code. The first step is finding a Qt API to control the rendering option.

**Comment by gwerbin** [comment]
I did some searching on this, because I would *love* a code text editor that supported modern OpenType features like stylistic sets, variations, etc.

It doesn't look like the Qt5 GUI `QFont` class supports any of that stuff, even though the underlying Freetype library naturally does. Some other programs (e.g. [Musescore](http://dev-list.musescore.org/Qt-and-OpenType-td7579162.html) and [QGIS](https://github.com/qgis/QGIS/issues/32733)) have long-standing open issues on this topic that have gone nowhere. Not what I was hoping to find.

That said, would it be possible, even in theory, to somehow bypass `QFont` (and forsake the platform-independence of the Qt ecosystem) and work with the system's font rendering stack directly? For example, on Linux you would have to directly use Freetype2 APIs. I have no idea if this can even be done, or how much work would be involved on each supported system...

**Comment by jgehrig** [comment]
Possible? Perhaps... Likely lots of work.

However, bypassing `QFont` would be a maintainability issue in the long-run. The code remains predicable and stable across platforms when we remain within the bounds of the Qt APIs. The current rendering logic is tightly coupled to Qt.

It might work for a personal fork, but I don't think that approach is something that could be merged in to the main code-base.

I'd recommend filing a bug fo Qt to support stylistic sets. We need a Qt API to support this feature officially (IMO).

**Comment by gwerbin** [comment]
https://bugreports.qt.io/browse/QTBUG-89958

I did a lot of searching and was surprised to not even see feature requests for this. The only insight was some StackOverflow answer from 2014 stating flatly that QFont did not support OpenType features. I assume this is just yelling into the void but hopefully something comes of this.

**Comment by jgehrig** [comment]
Marking this as closed.

Anyone who whats this feature should voice their opinions in the Qt bug above.

Sadly, it doesn't look like Qt will support stylistic set in `QFont` any time soon :/

**Comment by silmeth** [comment]
@jgehrig Seems that OpenType features like stylistic sets are going to be supported by `QFont` in Qt 6.6 (the [bug](https://bugreports.qt.io/browse/QTBUG-89958) status has been changed to *Closed: Fixed* on 2023-05-10 with Fix version `6.6.0 FF`).

Seems [this commit](https://github.com/qt/qtbase/commit/6160ea45b689e9d26795a18f155053ac4dc4dd6b) implements OpenType features.

**Comment by gwerbin** [comment]
Hey, that's my bug report!

I got an email notification about this a while ago. Very excited to see this coming.
