### ISSUE TITLE
Embedding neovim-qt in a PyQt application

### ISSUE THREAD

**Issue by irgolic** [equalsraf/neovim-qt#814]
Hey, I'm building a python script editor in PyQt5. Any chance I could embed neovim-qt as a text editor?

**Comment by jgehrig** [comment]
Marking this as closed, since it isn't directly related to `neovim-qt`. Feel free to keep posting here.

From some quick searching:
 - https://stackoverflow.com/questions/44258808/is-it-possible-to-embed-c-widget-to-pyqt-application
 - https://github.com/eyllanesc/Qt5toPyQt5

I'm not aware of anyone consuming neovim-qt in this way. I would guess this is possible, but may require some work on your end.

The `ShellWidget` is rather well isolated and should be consumable without too much work. It gets compiled into a separate library, `libqshellwidget`. However, `ShellWidget` does not have enough functionality to work as a standalone editor.

You may be able to embed the `Shell` widget, that would provide all of the necessary rendering logic. However, `Shell` wasn't written to be consumed outside of neovim-qt. You would likely run into dependency issues. You may need to modify the `CMake` logic and code for your application.

**Comment by irgolic** [comment]
Hey, thanks for the thorough response.

I think it could be done, but you'd have to build SIP bindings and ideally release on PyPi. If there's no one else interested but me, forget it.

It's interesting though, there seem to be quite a few solutions out there in C++, but none of them on PyPi.
