### ISSUE TITLE
Support strikethrough highlighting

### ISSUE THREAD

**Issue by Melkster** [equalsraf/neovim-qt#818]
neovim-qt doesn't seem to support ~strikethrough~ highlighting. Is there any plan to add this?

The following command outputs strikethrough text when running neovim in terminal, but not in neovim-qt:

```vim
:hi Foo cterm=strikethrough gui=strikethrough | hi Foo
```

**Comment by jgehrig** [comment]
The feature was added with: https://github.com/neovim/neovim/commit/3afb397407af3c94fc82d694186e8d451e625237

Yes, we should be able to easily support the feature. I was simply unaware of the new property, thanks for the ping.

**Comment by jgehrig** [comment]
Merged, marking as closed.

The `guifont` `:s` option doesn't work currently, #824. Implementation for `:s` (and `:u`) is tricky, due to the way we render underline and strikethrough. Fortunately, I can't image many users want underline or strikeout on every character...

Please let me know if you notice any issues. Thanks!

**Comment by p135246** [comment]
This is not working for me with vanilla nvim.
