### ISSUE TITLE
Cannot open file if it is in folder with space in name

### ISSUE THREAD

**Issue by Lodin** [equalsraf/neovim-qt#82]
**OS:** Ubuntu 14.04
**Qt:** 5.5.1

I use neovim-qt as main editor (it is specified as default editor loading by click on file). When I click on file lying under the folder which name contains space character, Neovim-qt freezes.

Reproducing:
* Create folder with name `test test`
* Create file with name `test.txt` under it.
* Load file (using nautilus by click)

Neovim freezes and offers to retry.

**Comment by equalsraf** [comment]
@Lodin how did you configure nautilus to open files with nvim-qt?

I'm unable to reproduce here, but I'm using pcman instead of nautilus. Can you check a couple of things?

- What parameters are passed to nvim-qt (ps ax | grep nvim-qt)
- Are you using the latest version? There was a bug fixed in 85dd35bf6dc5e294701cf92329c4ee0169f9bc8f that could cause us to freeze.

**Comment by Lodin** [comment]
@equalsraf through `Ubuntu Tweak` -> `Administration` -> `File types`, and then set nvim-qt as default editor for all files opening by gedit.

* `ps ax | grep nvim-qt`
```
/home/***/Programs/neovim-qt/build/bin/./nvim-qt /home/***/test test/test.txt
```
* Yes, I build nvim-qt from sources.

**Comment by Lodin** [comment]
@equalsraf Sorry, completely my bad. I use nvim-qt compiled from sources, so command to start and opening by click did by myself. And I passing parameters without blockquotes, so it is the root of the problem. I aplologize for disturbing you.

**Comment by equalsraf** [comment]
@Lodin no problem. The is now a desktop file in src/gui/nvim-qt.desktop, you might want to use it instead.
