### ISSUE TITLE
Issue New Release

### ISSUE THREAD

**Issue by thePHTest** [equalsraf/neovim-qt#831]
I am awaiting the latest release so I can set the window transparency.
Is there any chance a release could be made soon?
I attempted to build from source all day today but ran into a ton of issues getting Qt5.
The Qt5 installer failed due to not being able to verify a file hash. I then tried the portable Qt5 download and it failed to build and install after more than an hour of waiting on it.

Thanks, I appreciate the effort put into this tool.

**Comment by swag-lab** [comment]
Here's a link to the latest successful master build (from AppVeyor CI): https://ci.appveyor.com/api/buildjobs/1ln78jfo0r0cxuxq/artifacts/neovim-qt.zip

How to get the latest master build:
1. Go to the repository homepage.
2. Click on the "X commits" link just above the repo listing (here "X" means the number of commits till date).
3. Find the latest successful commit (indicated by :heavy_check_mark: green checkmark). Click on the checkmark.
4. Click on the "Details" link on the last CI (which says something like AppVeyor).
5. On the AppVeyor page, click on one of the toolchains (MSVC or GCC, both should work).
![screenshot 1](https://user-images.githubusercontent.com/79488680/113686277-b8149a80-96e4-11eb-8dd7-da2363463d2c.png)
6. Scroll down a bit on the next page, and click on the "Artifacts" tab.
![screenshot 2](https://user-images.githubusercontent.com/79488680/113686692-26f1f380-96e5-11eb-9f0b-f469e957c351.png)
7. Click on the generated zip file, and the file will start downloading.

I'm on Windows, so things might differ for you, but mostly it's the same :smiley:

And, the next release isn't yet done because there are some issues regarding ligatures and rendering: #771 #735 #412 #809 etc...

**Comment by jgehrig** [comment]
@swag-lab 

Thanks! Excellent write-up... Do you mind if I add your instructions as a page on the Wiki?

**One amendment:**
The :x: vs :heavy_check_mark: is not always a good indicator of a valid build. CodeCov regularly fails due to lack of test coverage (not a real failure).

Generally, I try to keep `master` in a good state. Enough folks run the latest build that it needs to be reasonably stable. Usually issues for existing features are reported, found, and fixed within a few days.

@thePHTest 

+1 to the comments above.

I would like to wait until ligatures are fixed, Neovim 0.5.0, and a few other features before the next release.

Closing this issue. However, feel free to keep commenting if you have trouble with `:GuiWindowOpacity`.

**Comment by swag-lab** [comment]
@jgehrig No. If the comment helped, I would me more than glad to have it in the Wiki. And thanks for the correction :smiley:

**Comment by thePHTest** [comment]
Thanks for the info on how to grab the latest release! It's working with one caveat. I had to copy the contents of the latest release here https://github.com/equalsraf/neovim-qt/releases (skipping anything that would overwrite) to get the required dlls, nvim.exe, etc.

**Comment by swag-lab** [comment]
Oh, didn't realize it. I just went to Neovim's installation directory, where two folders "bin" and "share" exist, and extracted the zip file to that path, **overwriting everything if need be**. This might be because Neovim already comes with a release version Neovim-qt. Not sure tho.

**Comment by thePHTest** [comment]
Ah yeah, that's a better way to do it. Thanks for the help everyone.
