### ISSUE TITLE
Shift-Backspace on Windows not working in latest commit  but works in Neovim Nightly

### ISSUE THREAD

**Issue by dseeni** [equalsraf/neovim-qt#886]
Hey equalsraf,

On windows with Nvim-qt via @Appveyor from this commit:
ed7a7dae52c4147d61cc953dc1a0ed97033a1c3b
Tried both mvsc and ming compiled versions

Latest Nvim-qt starts up 50ms faster though, so nice.

shift-BS shift backspace only registers as backspace

**However in Neovim nightly that version of Nvim-Qt things are working fine.**
Not sure how to compare the digraphs and see what key is being output.

**Comment by jgehrig** [comment]
@dseeni

Thanks for the bug report!

This is *arguably* a bug in the older version of `neovim-qt` (it sounds like you were using 0.2.16.1?).

Try the following:
1. Go into Insert Mode, `i`
2. Press `Ctrl + V`, `^` appears.
3. Press `Shift + BS`, `<BS>` appears.

I did some quick testing with the latest versions on Windows/Linux, and that is what I observed. (0.5.0 and 0.2.17.999/master).

Generally, we try to have neovim-qt match the behavior of Neovim. Marking this as closed, since our behavior in master matches Neovim.

---

This is somewhat arguable because Vim/gVim and Neovim do not behave the same.

From a quick test on Windows, gVim allows `<S-BS>` and Vim behaves nonsensically (inserts `Îy`).

If you feel strongly `<S-BS>` should be accepted, open a bug upstream in Neovim. We will follow the "TUI" Neovim behavior.

**Comment by dseeni** [comment]
Please have a look:
When I use Neovim Nightly v0.6.0dev with QT  0.2.16.1 Everything works **fine**

But with Neovim Nightly v0.6.0dev and NVIM-qt0.2.17.9999 
I lose shift+backspace and ctrl+shift+backspace as well as ctrl+shift+space

![image](https://user-images.githubusercontent.com/6591429/126107153-6bf1b46c-da52-47a7-8278-c705337d01c9.png)

**Comment by jgehrig** [comment]
I re-tested with Neovim 0.6.0. No observed diffrences from Neovim 0.5.0.

---

> Do I basically just need to learn how to compile it myself with Tui features?

No, you shouldn't need to compile anything.

TUI = Terminal UI

You're using the "TUI" when you run `nvim.exe` without `neovim-qt.exe`. Sorry for the un-explained acronyms/terminology.

---
> See here, the direct download from Neovim Nightly works perfectly for me but the new qt 2.17.999 doesn't

Please re-read the above again.

For 0.2.16, `<S-BS>` is a bug. The correct value for the key combination is `<BS>`.

For 0.2.17.9999, the bug has been fixed. The same applies to `Ctrl + Shift + Space`.

`<S-BS>` is a "bug" because `nvim-qt` and `nvim` have different behavior. We do our best to match the input of `nvim`.

If you can find a difference in behavior between `nvim` and `nvim-qt`, I'll fix the issue.

Please provide a clear set of steps staring with `nvim-qt -- -u NONE` and `nvim -u NONE` that has different end-results.

---

Here is the "bug":  #259 #728 

I use "bug" in quotes because gVim/Vim do not behave the same way as Neovim (from my testing).

You could argue this is an issue in Neovim's input layer. If they change, so will neovim-qt.

**Comment by dseeni** [comment]
Oh I see. Thank you for the explanation. 
I really liked the "bug" then in 0.2.16 :)

**Is there any way I can find out which keys have been "fixed" between nvim-qt 0.2.16 vs 0.2.17.9999?**

**Comment by jgehrig** [comment]
Yeah, sorry :)

I'm not sure why Neovim + Vim differ here...

There isn't a great list to point you to.

You can look through the commit logs. I've also added test coverage for any input fixes made recently. You'll find examples of `QKeyEvent` input and expected Vim sequence in `test/tst_input*.cpp`.

**Comment by dseeni** [comment]
Thanks for those tips, that should help!
