### ISSUE TITLE
[FEATURE REQUEST] Control + scroll for zoom in/out

### ISSUE THREAD

**Issue by grappas** [equalsraf/neovim-qt#913]

**Comment by jgehrig** [comment]
Thanks for the feature request!

I'm going to mark this as "Won't Fix", since this would conflict with `<C-ScrollWheelUp>`. Also we don't really have any concept of "zoom" other than to increase the font size.

If you want this behavior, you should be able to implement it some minimal VimScript:
```
:map <silent> <C-ScrollWheelUp> /*function to lookup and increment font size*/
:map <silent> <C-ScrollWhellDown> /*function to decrement font size*/
```

For the function, you can call `eval("GuiFont")`. Splice out the current number `:hXX` increment/decrement it and re-call `:GuiFont!...` with the newly modified value. You could also use `:set guifont` instead.

If arrive at an elegant solution, please post it here. That way other users looking for the same behavior can benefit :)

**Comment by jgehrig** [comment]
You could probably leverage this plugin:
https://github.com/vim-scripts/zoom.vim

```
:map <silent> <C-ScrollWheelUp> :ZoomIn<Enter>
:map <silent> <C-ScrollWhellDown> :ZoomOut<Enter>
```

**Comment by grappas** [comment]
@jgehrig Thanks. Worked like a charm. :)
