### ISSUE TITLE
nvim-lspconfig not working with neovim-qt

### ISSUE THREAD

**Issue by Cloudperry** [equalsraf/neovim-qt#932]
So nvim-lspconfig doesn't work with neovim-qt and it works just fine in terminal neovim. This can be easily checked by running :LspInfo in neovim and neovim-qt. In terminal neovim it doesn't error and in neovim-qt it errors with:
E5108: Error executing lua . . .nvim/plugged/nvim-lspconfig/lua/lspconfig/ui/windows.lua:106: Invalid key 'border' 

This also causes autocomplete with nvim-cmp and built-in lsp to not work. I tried this with both neovim and neovim-qt fresh from git and it doesn't change anything.

**Comment by jgehrig** [comment]
@Cloudperry

I cannot reproduce this issue (Linux or Windows). Since this is a plugin, could there be a configuration issue or conflict?

It would be helpful if you can provide a `minimal.vim` and set of instructions that reproduces the issue.

You can load `mininal.vim` with the command: `nvim-qt -- -u minimal.vim`.

**Comment by Cloudperry** [comment]
Yeah this is a weird one. I tried making a minimal config to reproduce this, but then I can't reproduce it. I will start looking into my normal init.lua to see what causes this.

**Comment by jgehrig** [comment]
This sounds like a configuration issue...

One long-shot idea:

Try running `nvim-qt -- somefile.txt` from your terminal. Our desktop shortcut is a little weird and opens files by passing them as arguments to `nvim`. I don't see how this would impact the scenario, but it is a possible difference between the cases.
