### ISSUE TITLE
Questions about build instructions

### ISSUE THREAD

**Issue by gwerbin** [equalsraf/neovim-qt#937]
I am basing my questions off of [the Build Instructions wiki page](https://github.com/equalsraf/neovim-qt/wiki/Build-Instructions), which have come up in the process of working on https://github.com/Homebrew/homebrew-core/pull/85526.

### `make install`

I see that CMake generates an `install` target for Make. Is this not safe or reliable to use for some reason? I don't see it mentioned in the docs anywhere.

Should I add this to the Build Instructions page?

Is it also OK if I mention CMake args like `-DCMAKE_INSTALL_PREFIX` there? A lot of users might not be familiar with CMake standards.

### `make` vs `cmake --build`

Does it matter if I run `cd build && make` or `cd build && cmake --build .` or `cmake --build build`?

### When is `NVIM_QT_RUNTIME_PATH` required?

Is `NVIM_QT_RUNTIME_PATH` only required when running from a location other than the installation prefix? I've never seemed to need it, but I'm not sure if I've been running a subtly-broken version all this time.

**Comment by jgehrig** [comment]
> I see that CMake generates an install target for Make. Is this not safe or reliable to use for some reason? I don't see it mentioned in the docs anywhere.

Sure, `make install` can be  used.

However, please do not advise users to run this command. Listing it as a footnote is fine.

I didn't list the command in the Wiki because on most systems, it better to use other means of install:
- Linux: Bundle into DEB/RPM and use the package manager.
- Windows: Copy-Paste the files into a directory, or use new the install wizard *.exe.
- MacOS: Use HomeBrew + tap command

I run Gentoo, so my package manager calls `make install` in a sandbox and then copies the files into the real filesystem. I'd guess HomeBrew does something similar. Most package wrap `make install` and each file added. This helps if the user ever want to uninstall .

> Should I add this to the Build Instructions page?
>
> Is it also OK if I mention CMake args like -DCMAKE_INSTALL_PREFIX there? A lot of users might not be familiar with CMake standards.

Sure! Please feel free to update the DOCS.

I'd appreciate a ping so I can proof-read the changes. You could create a dummy Pull Request with you updates, or ping me here in the Issue tracker.

> make vs cmake --build
>
> Does it matter if I run cd build && make or cd build && cmake --build . or cmake --build build?

No, all of those commands should work.

I've listed `cmake --build` because it is generator agnostic. You can use `cmake --build` on all build targets (Make, Ninja, Visual Studio).

I wanted to provide a command that works on all platforms, Windows/Mac/Linux. Feel free to use whatever the HomeBrew folks prefer.

>When is NVIM_QT_RUNTIME_PATH required?
>
> Is NVIM_QT_RUNTIME_PATH only required when running from a location other than the installation prefix? I've never seemed to need it, but I'm not sure if I've been running a subtly-broken version all this time.

Neovim-qt loads a vim plugin under-the-hood. This allows features like `:GuiFont` to work. `NVIM_QT_RUNTIME_PATH` is one method of telling the `nvim-qt` binary where to find this plugin.

By default, the `nvim-qt` executable looks for the plugin relative to the binary location. If you use `make install`, it should be able to find this plugin and this environment variable is not required.

`NVIM_QT_RUNTIME` is necessary when a non-standard install location is used. For example, when the user runs `nvim-qt` from their `build` directory without installing.

**Comment by jgehrig** [comment]
Marking as closed.

However, feel free to keep commenting! I'll watch this thread...

**Comment by gwerbin** [comment]
So in general, users building this application without a package manager should probably use `cmake --build` and `cmake --install`, whereas users packaging this application could use `make all` and `make install` instead of the CMake versions? Why wouldn't you always just use CMake to build and install?

Why have both? Are there circumstances where you would run CMake to generate the Makefile, and then distribute the source + Makefile so that you can build/install on systems without CMake?

> `NVIM_QT_RUNTIME` is necessary when a non-standard install location is used. For example, when the user runs `nvim-qt` from their build directory without installing.

Do you mind if I add these two exact sentences to the Building wiki page? This is a helpful clarification.

**Comment by jgehrig** [comment]
> So in general, users building this application without a package manager should probably use cmake --build and cmake --install, whereas users packaging this application could use make all and make install instead of the CMake versions? Why wouldn't you always just use CMake to build and install?

No, not exactly.

Commands `cmake --build` and `cmake --install` are wrappers. CMake is a meta-build-system, which generates build logic in one of a handful of tools (Make, Ninja, Visual Studio, etc).

A command like `cmake --build` triggers the correct build command for your chosen build tool under-the-hood. For example, it runs `make` if you've selected Make as your build tool.

It is easier to advise users to use `cmake --build` than trying to explain when and how to use which underlying build tool. For example, it is difficult to explain how to run a Visual Studio build to Windows users.

We do not mention `make install` or `cmake --install` in the Wiki because it may confuse new users. Usually, this is not a command you would want to run on a production machine since it subverts the regular package management mechanisms. However, it is perfectly safe to call in the context of packages like AUR, HomeBrew, or Portage. 

> Do you mind if I add these two exact sentences to the Build Instructions wiki page? This is a helpful clarification.

Sure! Clarification is always helpful... Contributions to documentation are alwasy welcomed! :+1: 

This is a common pain-point, it might make sense to update the [README](https://github.com/equalsraf/neovim-qt#why-are-the-gui-commands-missing)  too?

Please try to ping me, so I can proof read.
