### ISSUE TITLE
Ability to change the default background color of `guibg=none`

### ISSUE THREAD

**Issue by zeertzjq** [equalsraf/neovim-qt#942]
There are several reasons to use `guibg=none` instead of setting it to a color:
- Work around a glitch in TUI: <https://github.com/neovim/neovim/issues/7151> (<https://github.com/kovidgoyal/kitty/issues/4077>)
- Work around some other bugs, e.g., <https://github.com/neovim/neovim/issues/9019>

When using `guibg=none`, in TUI one can still easily change the background color by changing the background color of the terminal emulator, so a feature to change the default background color of `guibg=none` in GUI can be helpful (one can have the same background color in TUI and GUI).

**Comment by jgehrig** [comment]
Can you elaborate? What's the bug here? What is the feature request?

It would helpful for my understanding to provide:
1. A specific example where `neovim-qt` does not behave as you expect.
2. What you expect the behavior to be in the case above.

---

> in TUI one can still easily change the background color by changing the background color of the terminal emulator

We don't run in any terminal so this wouldn't exactly work for neovim-qt...

We *should* already support something like this. For any `:highlight` where a field does not have a color explicitly provided, we fallback to the default value for the active theme.

We also have to be careful here, we render whatever is reported by `nvim` through the [Neovim UI API](https://neovim.io/doc/user/ui.html).

That API already defines the behavior for an empty key value:
> For absent color keys the default color should be used. Don't store
> the default value in the table, rather a sentinel value, so that
> a changed default color will take effect.
> All boolean keys default to false, and will only be sent when they
> are true.

What you're asking might not be compatible with the way Neovim is currently written? (Not sure)

> (one can have the same background color in TUI and GUI).

If you're asking for the ability to set the background the same color as your terminal emulator, this is not possible.

We don't render within a terminal, and we don't have an API available to fetch this information. Too many terminals to support.

**Comment by zeertzjq** [comment]
Sorry for bothering.

**Comment by jgehrig** [comment]
No worries! Bug reports are always welcomed :)

**Comment by zeertzjq** [comment]
> We _should_ already support something like this. For any `:highlight` where a field does not have a color explicitly provided, we fallback to the default value for the active theme.

Does "default value" mean background color of `Normal`?

**Comment by jgehrig** [comment]
> Does "default value" mean background color of Normal?

Sort of. In this case, I meant the color defined in `default_colors_set`:
https://github.com/neovim/neovim/blob/ec4731d982031e363a59efd4566fc72234bb43c8/runtime/doc/ui.txt#L264

But yes, guess Neovim likely uses the values from `:hi Normal`.
